/* =========================================================================
   DISTANCIA — story.js
   Guión: Kenzo & Hana · Introducción + Capítulos 1–2
   (Capítulos 3–5 se agregan después.)

   El apartado `xml` de cada página es la FUENTE DE VERDAD visual:
   describe la escena; el motor la interpreta vía set/light/season/cast.

   page = {
     xml,                                  // nota de dirección (qué se ve)
     chapter?, chapterName?, chapterWhen?  // 1ª página del capítulo
     intro?[]                              // tarjeta de capítulo con varias líneas
     lead?[]                               // [TEXTO EN PANTALLA] en negro antes de la escena
     set, light, season, opts?            // escenario / luz / estación
     cast?: [{ who, pose, at, dim, w, dx, bottom }]
       who:  kenzo | hana | padre | hiro
       pose: stand | sit | back | hold | work
       at:   left | center | right
     dog?:  true | { pos, dx }
     prop?: 'cajita' | 'crane' | 'note' | 'box' | 'trampa'
     lines: [ N(t) | K(t,note) | H(t,note) | B(t) ]
     breakText?                            // interludio en negro tras la página
   }
   ========================================================================= */
const N = (t) => ({ s:'narrador', t });
const K = (t,note) => note ? ({s:'Kenzo', t, note}) : ({s:'Kenzo', t});
const H = (t,note) => note ? ({s:'Hana',  t, note}) : ({s:'Hana',  t});
const B = (t) => ({ s:'beat', t });

const STORY = [

/* ============================ INTRODUCCIÓN ============================ */
{ chapter:'Introducción', chapterName:'Antes de que empiece todo',
  lead:['Japón. Período Edo.', 'Aldea de Kuromi. Provincia de Shinano.', 'Año 1802.'],
  xml:'Aldea japonesa. Amanecer. Vista desde una colina: casas de madera, tejados de paja, el río entre campos de arroz, montañas al fondo. Humo de los primeros fogones subiendo recto.',
  set:'vista', light:'amanecer', season:'primavera', cast:[],
  lines:[
    N('Me llamo Kenzo.'),
    N('Tengo quince años y llevo toda mi vida en esta aldea.'),
    N('Kuromi no es grande ni importante.'),
    N('Es solo una aldea al pie de las montañas, a un día de camino de Matsumoto, la ciudad más cercana.'),
    N('Aquí todos se conocen, todos saben lo que hace el vecino, y las noticias viajan más rápido que cualquier mensajero.'),
  ]},

{ xml:'Interior de un taller de carpintería. Madera por todas partes, herramientas colgadas con orden. El padre de Kenzo trabajando; Kenzo adolescente sentado en el suelo con piezas desarmadas frente a él.',
  set:'taller', light:'dia', season:'primavera',
  cast:[{who:'padre', pose:'work', at:'right'}, {who:'kenzo', pose:'sit', at:'left'}],
  lines:[
    N('Mi padre es carpintero.'),
    N('Y su padre antes que él.'),
    N('No somos ricos, pero tampoco nos falta nada.'),
    N('Tenemos el taller, tenemos la casa, tenemos suficiente arroz para el invierno.'),
    N('Mi padre esperaba que yo aprendiera el oficio.'),
    N('Y lo aprendí.'),
    N('Pero lo que realmente me gustaba era desarmar las cosas para ver cómo funcionaban.'),
    N('Y luego armarlas diferente.'),
    N('A veces quedaban mejor.'),
    N('A veces no.'),
    N('Mi padre decía que eso no era carpintería.'),
    N('Probablemente tenía razón.'),
  ]},

{ xml:'Kenzo en el mercado de la aldea, hablando con varios, moviéndose entre los puestos con facilidad. Conoce a todos.',
  set:'mercado', light:'dia', season:'primavera',
  cast:[{who:'kenzo', pose:'stand', at:'center'}],
  lines:[
    N('En la aldea yo era conocido por dos cosas.'),
    N('Una: que nunca me quedaba callado cuando había algo que decir.'),
    N('Dos: que siempre tenía algo que decir.'),
    N('No era el más listo del lugar.'),
    N('Tampoco el más trabajador.'),
    N('Pero era bueno estando presente.'),
    N('En llenar los cuartos.'),
    N('En hacer que el tiempo pasara más rápido cuando estaba cerca.'),
    N('Eso a veces era un don.'),
    N('A veces era un problema.'),
    N('Dependía de a quién le preguntaras.'),
  ]},

{ xml:'Kenzo solo, de noche, sentado en el techo del taller mirando las estrellas. Abajo se escucha al padre trabajando todavía.',
  set:'techo', light:'noche', season:'primavera',
  cast:[{who:'kenzo', pose:'sit', at:'center'}],
  lines:[
    N('En ese entonces yo no pensaba mucho en el futuro.'),
    N('Pensaba en el día de hoy, en lo que había que hacer, en a quién ver.'),
    N('No sabía que ese año iba a cambiar bastante cosa.'),
    N('No sabía que iba a aparecer alguien que me iba a enseñar a quedarme quieto.'),
    N('O al menos a intentarlo.'),
  ]},

/* ============================ CAPÍTULO 1 ============================
   "El olor de las especias nuevas" */
{ chapter:'Capítulo 1', chapterName:'El olor de las especias nuevas', chapterWhen:'Primavera. Ella llega a la aldea.',
  xml:'Mercado de Kuromi. Mañana de primavera. Puestos de tela, especias, verduras, cerámica. Pétalos de cerezo entre los toldos. Kenzo cargando sacos para un vecino.',
  set:'mercado', light:'dia', season:'primavera',
  cast:[{who:'kenzo', pose:'stand', at:'center'}],
  lines:[
    N('Era una mañana de primavera como cualquier otra.'),
    N('Yo estaba ayudando a cargar sacos en el mercado.'),
    N('No era mi trabajo, pero el señor Tanaka siempre me daba algo de arroz a cambio.'),
    N('Y yo nunca le decía que no al arroz.'),
  ]},

{ xml:'Entre los puestos, una chica nueva. Kimono gris pálido, sencillo pero bien cuidado, cabello recogido con precisión. Parada frente al puesto de especias con una seriedad que no corresponde al mercado de una aldea pequeña.',
  set:'mercado', light:'dia', season:'primavera',
  cast:[{who:'hana', pose:'stand', at:'center'}],
  lines:[
    N('Ahí fue cuando la vi por primera vez.'),
    N('Estaba frente al puesto de especias del señor Mori.'),
    N('Oliendo cada una.'),
    N('Una por una.'),
    N('Con la cara de alguien que está tomando una decisión muy importante.'),
    N('Aunque fueran especias.'),
  ]},

{ xml:'Hana huele una especia y niega casi imperceptiblemente. El señor Mori la mira sin saber qué decir. Ella huele otra. La aparta también.',
  set:'mercado', light:'dia', season:'primavera',
  cast:[{who:'hana', pose:'stand', at:'center'}],
  lines:[
    N('El señor Mori se veía confundido.'),
    N('Nadie en Kuromi olía las especias antes de comprarlas.'),
    N('La gente de aquí compraba lo que había y ya.'),
    N('Esta chica claramente no era de aquí.'),
  ]},

{ xml:'Hana encuentra una especia que le convence, la huele dos veces para confirmar, asiente. Saca un papel doblado — una lista de caligrafía precisa. Revisa algo, lo dobla de vuelta con exactitud y sigue.',
  set:'mercado', light:'dia', season:'primavera',
  cast:[{who:'hana', pose:'hold', at:'center'}],
  lines:[
    N('Compró una sola.'),
    N('Luego sacó una lista.'),
    N('Escrita con más cuidado que cualquier documento oficial que yo hubiera visto.'),
    N('La dobló en exactamente los mismos dobleces de antes.'),
    N('Y siguió su camino como si el mercado entero fuera un trámite necesario.'),
  ]},

{ xml:'Hana pasa cerca de Kenzo sin verlo. A él se le cae un saco justo en ese momento — ruido ridículo. Ella voltea un segundo, lo mira, lo evalúa, sigue caminando.',
  set:'mercado', light:'dia', season:'primavera',
  cast:[{who:'kenzo', pose:'stand', at:'left'}, {who:'hana', pose:'stand', at:'right'}],
  lines:[
    N('Pasó a mi lado justo cuando se me cayó un saco.'),
    N('Hizo un ruido bastante ridículo.'),
    N('Ella volteó.'),
    N('Me miró un segundo.'),
    N('Y siguió caminando.'),
    N('Sin decir nada.'),
    N('Sin reírse.'),
    N('Solo me vio y decidió que no valía la pena comentarlo.'),
    N('Eso también me lo guardaría después.'),
  ]},

{ xml:'Kenzo parado con el saco en el suelo. El señor Tanaka lo mira desde el puesto. Kenzo recoge el saco pero sigue mirando hacia donde ella se fue.',
  set:'mercado', light:'dia', season:'primavera',
  cast:[{who:'kenzo', pose:'stand', at:'center'}],
  lines:[
    N('Me quedé parado con el saco en la mano.'),
    N('El señor Tanaka me gritó que me apurara.'),
    N('Me apuré.'),
    N('Pero volteé tres veces hacia donde había ido.'),
    N('Ya no estaba.'),
  ]},

{ xml:'Tarde. Kenzo en el río — el lugar donde va a pensar. Sentado en la orilla, el cubo a su lado, el río tranquilo.',
  set:'rio', light:'tarde', season:'primavera', opts:{sun:true, tree:'sakura'},
  cast:[{who:'kenzo', pose:'sit', at:'center'}],
  lines:[
    N('Esa tarde fui al río.'),
    N('Que es donde voy cuando tengo algo dando vueltas en la cabeza.'),
    N('No sabía quién era ella.'),
    N('No sabía de dónde venía.'),
    N('Solo sabía que había rechazado seis especias seguidas con total convicción.'),
    N('Y que cuando se me cayó el saco me miró como si eso fuera lo más predecible del mundo.'),
    N('Y por alguna razón eso me pareció lo más interesante que había pasado en semanas.'),
  ]},

{ xml:'Noche. Kenzo en el techo del taller, mirando las estrellas. Esta vez pensando en ella.',
  set:'techo', light:'noche', season:'primavera',
  cast:[{who:'kenzo', pose:'sit', at:'center'}],
  lines:[
    N('Esa noche, acostado en el techo como siempre, me pregunté varias cosas.'),
    N('Cómo se llamaba.'),
    N('Por qué había llegado a Kuromi.'),
    N('Qué hacía con las especias que sí aprobaba.'),
    N('Si tenía esa misma cara para todo.'),
    N('Cosas sin importancia.'),
    N('Pero muchas cosas sin importancia al mismo tiempo ya es algo.'),
  ]},

{ lead:['Días después.'],
  xml:'Mercado. Kenzo buscando sin parecer que busca. La ve al fondo, esta vez en el puesto de verduras, con el mismo criterio de siempre.',
  set:'mercado', light:'dia', season:'primavera',
  cast:[{who:'kenzo', pose:'stand', at:'left'}, {who:'hana', pose:'stand', at:'right'}],
  lines:[
    N('Los días siguientes la fui viendo por la aldea.'),
    N('Siempre en lo suyo.'),
    N('Siempre con esa concentración de alguien que tiene cosas importantes que resolver.'),
    N('Aunque fueran verduras.'),
    N('Un día la vi rechazar tres zanahorias seguidas.'),
    N('El vendedor se veía ofendido.'),
    N('Ella no.'),
  ]},

{ xml:'Camino al río. Tarde. Kenzo va con el cubo. La ve venir en dirección contraria, cargando manojos de hierbas atadas con precisión. Un perro mediano va adelante.',
  set:'camino', light:'tarde', season:'primavera', opts:{tree:'sakura'},
  cast:[{who:'hana', pose:'hold', at:'center'}], dog:{pos:'center', dx:78},
  lines:[
    N('Una tarde la vi venir por el mismo camino que yo.'),
    N('Cargaba hierbas.'),
    N('Muchas hierbas.'),
    N('Cada tipo amarrado por separado.'),
    N('Con un perro adelante que caminaba como si supiera a dónde iban.'),
  ]},

{ xml:'Kenzo cambia ligeramente su ruta para cruzarse. A mitad del ajuste se da cuenta de lo que hace. Ya es tarde para deshacerlo sin que se vea raro.',
  set:'camino', light:'tarde', season:'primavera', opts:{tree:'sakura'},
  cast:[{who:'kenzo', pose:'stand', at:'center'}],
  lines:[
    N('Cambié un poco mi ruta para que el camino coincidiera.'),
    N('A mitad del cambio me di cuenta de lo que estaba haciendo.'),
    N('Ya era tarde para arreglarlo sin verme más ridículo.'),
    N('Así que seguí.'),
  ]},

{ xml:'Se cruzan. El perro llega a Kenzo primero, lo olfatea. Hana levanta la vista de las hierbas; lo reconoce del mercado. Kenzo sostiene el cubo con más fuerza de la necesaria.',
  set:'camino', light:'tarde', season:'primavera', opts:{tree:'sakura'},
  cast:[{who:'kenzo', pose:'stand', at:'left'}, {who:'hana', pose:'hold', at:'right'}], dog:{pos:'center', dx:0},
  lines:[
    K('Buenas tardes.'),
    H('Buenas tardes.', '(un segundo antes de responder)'),
    K('¿Eres nueva en la aldea? No te había visto antes.'),
    N('Mentira.'),
    N('La había visto cuatro veces.'),
    N('Pero no podía decir eso.'),
  ]},

{ xml:'Hana responde sin dejar de revisar las hierbas con la mano libre. El perro olfatea a Kenzo; él intenta acariciarlo y el perro lo ignora.',
  set:'camino', light:'tarde', season:'primavera', opts:{tree:'sakura'},
  cast:[{who:'kenzo', pose:'stand', at:'left'}, {who:'hana', pose:'hold', at:'right'}], dog:{pos:'center', dx:0},
  lines:[
    H('Llegué hace un mes con mi padre.'),
    K('¿Y cómo te ha parecido la aldea?'),
    H('Las hierbas del mercado no están bien conservadas. Pierden propiedades.', '(lo piensa de verdad)'),
    K('...Ah.'),
    N('Eso no era lo que esperaba.'),
    N('Esperaba algo sobre el clima.'),
    N('O sobre la gente.'),
    N('Las hierbas no.'),
  ]},

{ xml:'Hana espera que la conversación termine. Kenzo sonríe sin querer; ella nota la sonrisa y frunce levemente el ceño, genuinamente confundida.',
  set:'camino', light:'tarde', season:'primavera', opts:{tree:'sakura'},
  cast:[{who:'kenzo', pose:'stand', at:'left'}, {who:'hana', pose:'stand', at:'right'}], dog:{pos:'center', dx:0},
  lines:[
    H('¿Qué?'),
    K('Nada. Es que... pregunté cómo te había parecido la aldea.'),
    H('Y eso es lo que me ha parecido.'),
    K('Las hierbas.'),
    H('Las hierbas importan.'),
    N('No había ironía.'),
    N('No era un chiste.'),
    N('Era completamente en serio.'),
    N('Y por alguna razón eso fue lo más refrescante que alguien me había dicho en mucho tiempo.'),
  ]},

{ xml:'Hana llama al perro con un silbido corto; el perro obedece de inmediato. Hace un pequeño gesto de despedida y sigue su camino. Kenzo se queda con el cubo.',
  set:'camino', light:'atardecer', season:'primavera', opts:{tree:'sakura'},
  cast:[{who:'kenzo', pose:'stand', at:'left'}, {who:'hana', pose:'back', at:'right'}], dog:{pos:'right', dx:-30},
  lines:[
    N('Se fue.'),
    N('Sin más.'),
    N('El perro la siguió sin que nadie se lo dijera dos veces.'),
    N('Yo me quedé parado en el camino.'),
    N('Con el cubo.'),
    N('Mirando hacia donde había ido.'),
    K('Las hierbas importan.', '(en voz baja, solo para él)'),
    N('No supe si reírme o qué.'),
    N('Me reí.'),
  ]},

{ xml:'Kenzo llega al río, se sienta, el cubo a su lado. El río tranquilo. Tarde de primavera.',
  set:'rio', light:'tarde', season:'primavera', opts:{sun:true, tree:'sakura'},
  cast:[{who:'kenzo', pose:'sit', at:'center'}],
  lines:[
    N('Llegué al río y me di cuenta que no recordaba bien para qué había venido.'),
    N('El cubo estaba vacío todavía.'),
    N('Lo llené.'),
    N('Me senté un rato de más.'),
    N('Pensando en una chica que no sé cómo se llama que rechaza especias y dice que las hierbas importan.'),
    N('Y tiene razón, probablemente.'),
    N('Las hierbas importan.'),
  ]},

/* ============================ CAPÍTULO 2 ============================
   "Lo que no se decide" */
{ chapter:'Capítulo 2', chapterName:'Lo que no se decide', chapterWhen:'Primavera a otoño. Dos personas volviéndose costumbre una para la otra.',
  lead:['Las semanas siguientes.', 'Kenzo empieza a tener muchas razones para ir al río.', 'Todas inventadas.'],
  xml:'El río, mañana. Kenzo ya está ahí con su cubo, llegó antes de lo necesario. Hana aparece por el otro lado con su cesta de hierbas; el perro adelante.',
  set:'rio', light:'dia', season:'primavera', opts:{tree:'sakura', ducks:true},
  cast:[{who:'kenzo', pose:'sit', at:'left'}, {who:'hana', pose:'hold', at:'right'}], dog:{pos:'center', dx:0},
  lines:[
    N('Empecé a ir al río más temprano.'),
    N('Por el agua.'),
    N('Obviamente por el agua.'),
    N('El cubo lo confirmaba.'),
    N('El hecho de que llegara media hora antes de lo necesario era una coincidencia.'),
    N('Una coincidencia que ocurría todos los días.'),
  ]},

{ xml:'Hana llega y se sienta a unos metros. Empieza a separar hierbas sin decir nada. El perro se queda entre los dos.',
  set:'rio', light:'dia', season:'primavera', opts:{tree:'sakura'},
  cast:[{who:'kenzo', pose:'sit', at:'left'}, {who:'hana', pose:'sit', at:'right'}], dog:{pos:'center', dx:0},
  lines:[
    N('Llegabas y te sentabas.'),
    N('Sin invitarme.'),
    N('Sin pedirme que me fuera.'),
    N('Y empezabas con las hierbas como si fuera lo más normal del mundo que yo estuviera ahí.'),
    N('No sé cuándo dejó de ser raro.'),
    N('Solo dejó de serlo.'),
  ]},

{ xml:'Kenzo intenta ayudar — recoge una hierba y se la extiende con confianza. Hana la mira. La deja en el suelo.',
  set:'rio', light:'dia', season:'primavera', opts:{tree:'sakura'},
  cast:[{who:'kenzo', pose:'sit', at:'left'}, {who:'hana', pose:'sit', at:'right'}], dog:{pos:'center', dx:0},
  lines:[
    K('¿Esta no sirve?'),
    H('Está cortada mal.'),
    K('¿Cómo se corta mal una hierba?'),
    H('De muchas maneras.', '(como si la respuesta fuera obvia)'),
    N('Dejé la hierba en el suelo.'),
    N('No volví a recoger hierbas.'),
    N('Aprendí rápido en eso.'),
  ]},

{ xml:'Los dos en silencio. El río. El perro dormido.',
  set:'rio', light:'tarde', season:'primavera', opts:{tree:'sakura'},
  cast:[{who:'kenzo', pose:'sit', at:'left'}, {who:'hana', pose:'sit', at:'right'}], dog:{pos:'center', dx:0},
  lines:[
    N('Nos quedábamos en silencio seguido.'),
    N('Para mí el silencio siempre fue algo que había que llenar.'),
    N('Con ella era diferente.'),
    N('No pesaba.'),
    N('Solo era silencio.'),
    N('Así que lo dejé estar.'),
    N('Que para mí seguía siendo mucho.'),
  ]},

{ xml:'Kenzo no aguanta más. Abre la boca.',
  set:'rio', light:'tarde', season:'primavera', opts:{tree:'sakura'},
  cast:[{who:'kenzo', pose:'sit', at:'left'}, {who:'hana', pose:'sit', at:'right'}], dog:{pos:'center', dx:0},
  lines:[
    K('Hana.'),
    H('¿Qué?', '(sin levantar la vista)'),
    K('¿Cómo sabes cuándo una hierba está mal cortada?'),
    H('Por el corte.', '(pausa)'),
    K('Eso no me ayuda.'),
    H('Lo sé.'),
    N('No sé si fue un chiste.'),
    N('Nunca supe con certeza.'),
    N('Pero me reí.'),
    N('Ella siguió con las hierbas.'),
  ]},

{ lead:['Días después.', 'Las escaleras del templo.'],
  xml:'Hana sentada en las escaleras del templo doblando papel de arroz. Varios terminados a su lado. El perro a sus pies. Kenzo pasaba por ahí y se detiene.',
  set:'templo', light:'tarde', season:'primavera', opts:{night:false},
  cast:[{who:'kenzo', pose:'sit', at:'left'}, {who:'hana', pose:'sit', at:'right'}], dog:{pos:'right', dx:-30},
  lines:[
    N('La encontré en las escaleras del templo un día.'),
    N('Doblando papel.'),
    N('Con esa seriedad que le ponía a todo.'),
    N('Me senté sin que nadie me lo ofreciera.'),
    N('Como siempre.'),
  ]},

{ xml:'Kenzo observa. Hana termina una figura, la examina. Algo está un milímetro torcido, invisible para cualquiera. La deshace. Empieza de nuevo.',
  set:'templo', light:'tarde', season:'primavera', opts:{night:false},
  cast:[{who:'kenzo', pose:'sit', at:'left'}, {who:'hana', pose:'sit', at:'right'}],
  lines:[
    K('¿Por qué la deshiciste? Estaba bien.'),
    H('No estaba bien.'),
    K('Yo no vi nada mal.'),
    H('Por eso tú no la estás haciendo.'),
    N('No tuve respuesta para eso.'),
    N('Porque era verdad.'),
  ]},

{ xml:'Kenzo decide demostrar que tiene paciencia. Se cruza de brazos. Se queda callado. Hana sigue doblando. Treinta segundos. Un minuto.',
  set:'templo', light:'tarde', season:'primavera', opts:{night:false},
  cast:[{who:'kenzo', pose:'sit', at:'left'}, {who:'hana', pose:'sit', at:'right'}],
  lines:[
    N('Me propuse quedarme callado para demostrar algo.'),
    N('No sé exactamente qué.'),
    N('A los dos minutos casi pregunté si las figuras tenían nombres.'),
    N('Me lo aguanté.'),
    N('A los tres minutos casi pregunté cuántas podía hacer en un día.'),
    N('También me lo aguanté.'),
    N('A los cuatro minutos ella dijo:'),
    H('Ya puedes preguntar lo que quieras.'),
    K('¿Cómo supiste?'),
    H('Llevas cuatro minutos respirando diferente.'),
    N('No supe qué hacer con esa información.'),
    N('Pero me gustó que me hubiera notado.'),
  ]},

{ lead:['El festival menor de la aldea.'],
  xml:'Festival. Linternas, música, gente. Kenzo adentro en su elemento total. La busca sin proponérselo; no está.',
  set:'festival', light:'noche', season:'verano',
  cast:[{who:'kenzo', pose:'stand', at:'center'}],
  lines:[
    N('El festival de mitad de primavera era el más chico del año.'),
    N('Pero en Kuromi cualquier razón para poner linternas era bienvenida.'),
    N('Yo estaba adentro, como siempre.'),
    N('En mi elemento.'),
    N('Y sin querer la busqué entre la gente.'),
    N('No estaba.'),
    N('Supe exactamente dónde buscar.'),
  ]},

{ xml:'Hana en el puente de piedra. Tranquila. El perro a su lado. El festival a lo lejos.',
  set:'puente', light:'noche', season:'verano',
  cast:[{who:'kenzo', pose:'stand', at:'left'}, {who:'hana', pose:'sit', at:'right'}], dog:{pos:'right', dx:-10},
  lines:[
    K('¿No entras?'),
    H('Estoy bien aquí.'),
    K('Hay bastante gente adentro.'),
    H('Lo sé.'),
    K('¿No te gusta la gente?'),
    H('Me gusta la gente. No me gusta mucha gente junta en un espacio chico.'),
    K('Es un festival.'),
    H('Exacto.'),
    N('Me senté en el puente sin que me lo ofrecieran.'),
    N('Como siempre.'),
    N('Le hizo un pequeño espacio al perro para que no estuviera entre los dos.'),
    N('No sé si fue intencional.'),
    N('Probablemente no lo iba a admitir.'),
  ]},

{ xml:'Los dos en el puente. Kenzo señala cosas que pasan adentro — el señor Tanaka bailando mal. Hana mira con más interés del que admite.',
  set:'puente', light:'noche', season:'verano',
  cast:[{who:'kenzo', pose:'sit', at:'left'}, {who:'hana', pose:'sit', at:'right'}], dog:{pos:'center', dx:0},
  lines:[
    K('Mira al señor Tanaka.'),
    H('¿Qué tiene?', '(sin voltear del todo)'),
    K('Está bailando.'),
    H('Ah.'),
    K('Muy mal.'),
    H('¿Qué tan mal?', '(voltea apenas)'),
    K('Bastante.'),
    N('Te giraste un poco más para verlo mejor.'),
    N('Pero muy despacio.'),
    N('Como si no quisieras que yo notara que querías ver.'),
    N('Lo noté.'),
    N('No dije nada.'),
  ]},

{ xml:'El perro, aburrido, se mete entre los dos de nuevo. Se echa encima del pie de Kenzo.',
  set:'puente', light:'noche', season:'verano',
  cast:[{who:'kenzo', pose:'sit', at:'left'}, {who:'hana', pose:'sit', at:'right'}], dog:{pos:'center', dx:0},
  lines:[
    N('El perro se metió entre los dos y se echó encima de mi pie.'),
    N('No me moví para no despertarlo.'),
    H('Puedes moverlo.'),
    K('Ya sé. Pero no me molesta.'),
    H('Le haces muy fácil la vida.', '(lo mira un momento)'),
    K('¿Y eso está mal?'),
    H('No.', '(regresa a ver el festival)'),
    N('Creo que eso tampoco era solo sobre el perro.'),
  ]},

{ lead:['Semanas después.', 'El río del norte.'],
  xml:'Los dos caminando al río del norte, más lejos, entre árboles. El perro adelante. Hana explicando algo sobre las plantas mientras camina.',
  set:'camino', light:'dia', season:'verano', opts:{tree:'sakura'},
  cast:[{who:'kenzo', pose:'stand', at:'left'}, {who:'hana', pose:'hold', at:'right'}], dog:{pos:'center', dx:0},
  lines:[
    N('Me mandaste una nota diciendo que las hierbas del río del norte eran mejores.'),
    N('Y que si quería acompañarte, podía.'),
    N('Una invitación de cuatro palabras disfrazada de información botánica.'),
    N('Fui obviamente.'),
  ]},

{ xml:'A la orilla del río del norte. Hana recoge hierbas. Kenzo intenta ayudar — mejor que antes pero no mucho. Ella le dice que huela.',
  set:'rio', light:'dia', season:'verano', opts:{tree:'sakura', ducks:true, hill:'#7e8f5a', frontBank:'#8aa066'},
  cast:[{who:'kenzo', pose:'sit', at:'left'}, {who:'hana', pose:'hold', at:'right'}], dog:{pos:'center', dx:0},
  lines:[
    H('Esta sí.'),
    K('¿Y esta?'),
    H('No.'),
    K('¿Por qué no? Se ve igual que la otra.'),
    H('No se ve igual.'),
    K('Para mí sí.'),
    H('Huélelas.', '(decide algo)'),
    N('Las olí. No distinguí nada. Pero no lo iba a admitir.'),
    K('Ah. Sí. Esta huele diferente.'),
    H('¿A qué huele diferente?'),
    K('A... más verde.', '(pausa larga)'),
    H('A más verde.', '(lo mira)'),
    K('Sí.'),
    N('No dijo nada.'),
    N('Pero hubo algo en su cara que no había visto antes.'),
    N('Creo que fue la primera vez que casi se rió de algo que yo dije.'),
    N('Casi.'),
  ]},

{ xml:'Sentados a la orilla. Silencio cómodo. El perro duerme.',
  set:'rio', light:'tarde', season:'verano', opts:{tree:'sakura'},
  cast:[{who:'kenzo', pose:'sit', at:'left'}, {who:'hana', pose:'sit', at:'right'}], dog:{pos:'center', dx:0},
  lines:[
    K('¿Por qué siempre doblas el papel igual?'),
    H('Porque si lo doblas diferente cada vez, al final no sabes dónde está lo importante.', '(piensa antes de responder)'),
    N('Me quedé pensando en eso más tiempo del que esperaba.'),
    N('Podía ser sobre el papel.'),
    N('O podía no ser solo sobre el papel.'),
    N('Con ella nunca estaba completamente seguro.'),
  ]},

{ xml:'Kenzo intenta doblar una hoja del suelo. Queda torcida. Hana se acerca y le mueve los dedos a donde deben estar.',
  set:'rio', light:'tarde', season:'verano', opts:{tree:'sakura'},
  cast:[{who:'kenzo', pose:'sit', at:'left'}, {who:'hana', pose:'sit', at:'right'}],
  lines:[
    H('¿Qué estás haciendo?'),
    K('Practicando.'),
    H('¿El qué?'),
    K('El doblez ese del inicio.'),
    H('Eso no es el doblez del inicio.'),
    K('Por eso estoy practicando.'),
    N('Se acercó.'),
    N('Sin decir nada, movió mis dedos a donde debían estar.'),
    N('El doblez quedó mejor.'),
    N('No perfecto.'),
    N('Pero yo en ese momento estaba pensando en otra cosa completamente.'),
    N('Y fue cuando entendí que tenía un problema serio.'),
  ]},

{ lead:['El juego de piedras.', 'Una tarde de verano.'],
  xml:'Los dos en el río. Kenzo saca unas piedras planas — un juego de posición que todos en Kuromi saben jugar. Lo pone entre los dos.',
  set:'rio', light:'tarde', season:'verano', opts:{sun:true, tree:'sakura'},
  cast:[{who:'kenzo', pose:'sit', at:'left'}, {who:'hana', pose:'sit', at:'right'}], prop:'piedras',
  lines:[
    N('Un día llevé un juego.'),
    N('Piedras planas.'),
    N('Un juego de posición que todo mundo en Kuromi sabía jugar.'),
    N('O casi todo mundo.'),
  ]},

{ xml:'Kenzo explica las reglas. Hana escucha con atención. Empiezan a jugar. Hana es malísima.',
  set:'rio', light:'tarde', season:'verano', opts:{tree:'sakura'},
  cast:[{who:'kenzo', pose:'sit', at:'left'}, {who:'hana', pose:'sit', at:'right'}], prop:'piedras',
  lines:[
    N('Explicaste las reglas y empezamos.'),
    N('Y descubrí algo en los primeros tres minutos:'),
    N('Hana era malísima.'),
    N('No un poco.'),
    N('Considerablemente.'),
  ]},

{ xml:'Kenzo gana fácilmente. Hana mira el tablero con su cara analítica, pero el análisis no llega a ningún lado.',
  set:'rio', light:'tarde', season:'verano', opts:{tree:'sakura'},
  cast:[{who:'kenzo', pose:'sit', at:'left'}, {who:'hana', pose:'sit', at:'right'}], prop:'piedras',
  lines:[
    K('¿Quieres otra?'),
    H('Sí.', '(estudiando las piedras)'),
    N('Jugamos cuatro veces.'),
    N('Gané las cuatro. Fácil.'),
    N('Hana no era de las que se rendían.'),
    N('Pero tampoco mejoraba tan rápido en esto.'),
    N('Y lo que me pareció interesante fue que no le molestó perder.'),
    N('Solo seguía viendo el tablero como un problema de hierbas que eventualmente iba a resolver.'),
  ]},

{ xml:'Quinta partida. Kenzo le ayuda discretamente para que dure más. Hana lo nota.',
  set:'rio', light:'atardecer', season:'verano', opts:{tree:'sakura'},
  cast:[{who:'kenzo', pose:'sit', at:'left'}, {who:'hana', pose:'sit', at:'right'}], prop:'piedras',
  lines:[
    K('Otra vez.'),
    H('¿Me estás ayudando?', '(sin levantar la vista del tablero)'),
    K('No.'),
    H('Kenzo.', '(lo mira)'),
    K('Solo un poco.'),
    H('No hagas eso.'),
    K('¿Por qué no? Si no te ayudo pierdes en dos minutos.'),
    H('Lo sé. Pero prefiero perder sola que ganar con ayuda.'),
    N('Eso también lo guardé.'),
    N('Porque decía mucho sobre cómo era ella.'),
  ]},

{ lead:['El día de los temperamentos.'],
  xml:'Kenzo llega al río con un papel — un texto que dejó un viajero, sobre tipos de temperamento de un filósofo del continente. Se lo extiende a Hana.',
  set:'rio', light:'tarde', season:'verano', opts:{tree:'sakura'},
  cast:[{who:'kenzo', pose:'sit', at:'left'}, {who:'hana', pose:'sit', at:'right'}], prop:'note',
  lines:[
    N('Un viajero dejó un texto en el taller.'),
    N('Sobre tipos de temperamento.'),
    N('No sé por qué lo llevé al río.'),
    N('Mentira, sí sé.'),
    N('Lo llevé porque cuando lo leí pensé en Hana en cada segunda línea.'),
  ]},

{ xml:'Hana lo lee completo, sin prisa. Kenzo espera. Luego se lo devuelve.',
  set:'rio', light:'tarde', season:'verano', opts:{tree:'sakura'},
  cast:[{who:'kenzo', pose:'sit', at:'left'}, {who:'hana', pose:'sit', at:'right'}],
  lines:[
    N('Lo leíste completo.'),
    N('Que con Hana significaba que algo le importó.'),
    N('Cuando algo no le importaba, lo devolvía rápido.'),
    K('¿Qué piensas?'),
    H('¿Por qué me lo trajiste?', '(pausa)'),
    K('Porque dice que un tipo y otro tipo funcionan bien juntos.'),
    H('Lo leí.'),
    K('¿Y?'),
    H('Es un texto viejo de alguien que no nos conoce.', '(mira el río)'),
    K('Sí. Pero acierta bastante.'),
    H('En algunas cosas.'),
    K('¿En cuáles?'),
    H('En que uno complementa lo que al otro le falta.'),
    N('No dijiste más. Yo tampoco.'),
    N('El río siguió corriendo.'),
    N('Y los dos nos quedamos con lo que eso significaba.'),
    N('Sin nombrarlo. Que también era nuestra manera.'),
  ]},

{ lead:['El día que Kenzo intentó cocinar.'],
  xml:'Cocina de la casa de Kenzo, el taller al fondo. Él en la cocina con ingredientes sobre la mesa, decidido a preparar algo. El perro mirándolo.',
  set:'cocina', light:'tarde', season:'verano',
  cast:[{who:'kenzo', pose:'stand', at:'center'}], dog:{pos:'right', dx:-30},
  lines:[
    N('Un día decidí cocinar.'),
    N('No sé bien qué me dio esa idea.'),
    N('Hana siempre traía comida.'),
    N('Y yo pensé: puedo hacer eso.'),
    N('No puedo hacer eso.'),
  ]},

{ xml:'Kenzo cocinando con demasiada confianza para alguien que no cocina. El perro lo sigue. El resultado huele raro.',
  set:'cocina', light:'tarde', season:'verano',
  cast:[{who:'kenzo', pose:'stand', at:'center'}], dog:{pos:'left', dx:30},
  lines:[
    N('El problema no fue el ingrediente.'),
    N('El problema fue la proporción.'),
    N('Y el orden.'),
    N('Y el tiempo.'),
    N('Básicamente todo.'),
  ]},

{ xml:'Hana llega. Entra. Huele algo. Mira a Kenzo. Mira la olla. Mira a Kenzo otra vez.',
  set:'cocina', light:'tarde', season:'verano',
  cast:[{who:'kenzo', pose:'stand', at:'left'}, {who:'hana', pose:'stand', at:'right'}],
  lines:[
    H('¿Qué es eso?'),
    K('Comida.'),
    H('¿Seguro?', '(se acerca a ver)'),
    K('Está bien. Solo necesita un poco más de tiempo.'),
    H('¿Cuánto pusiste de esto?', '(lo huele con cuidado)'),
    K('Lo suficiente.'),
    H('¿Cuánto es lo suficiente?'),
    K('...Lo que me pareció suficiente.'),
    N('Cerró los ojos un segundo.'),
    N('Como cuando algo te estresa pero decides no decirlo.'),
    N('Luego los abrió.'),
    N('Y empezó a corregir.'),
  ]},

{ xml:'Hana en la cocina, en su elemento. Reorganiza, agrega, ajusta. Kenzo la mira. El perro roba algo de la mesa.',
  set:'cocina', light:'tarde', season:'verano',
  cast:[{who:'kenzo', pose:'stand', at:'left'}, {who:'hana', pose:'stand', at:'right'}], dog:{pos:'left', dx:-10},
  lines:[
    N('El perro se robó algo de la mesa mientras los dos veíamos la olla.'),
    N('Ninguno lo vio a tiempo.'),
    H('Tu perro se robó el jengibre.', '(sin voltear)'),
    K('No es mi perro.'),
    H('Te sigue a ti.'),
    K('Te sigue a ti más.'),
    H('Cuando hay comida te sigue a ti.', '(lo mira)'),
    N('Eso era verdad. No tenía respuesta.'),
  ]},

{ xml:'Hana termina de corregir la olla. Sirve. Se lo da a Kenzo. Lo prueba. Es bueno.',
  set:'cocina', light:'tarde', season:'verano',
  cast:[{who:'kenzo', pose:'stand', at:'left'}, {who:'hana', pose:'stand', at:'right'}],
  lines:[
    K('Está muy bueno.'),
    H('Lo sé.'),
    K('O sea, yo puse los ingredientes.'),
    H('Yo los arreglé.'),
    K('Fue trabajo en equipo.'),
    H('Kenzo.', '(lo mira)'),
    K('¿Qué?'),
    H('No fue trabajo en equipo.'),
    N('Comimos los dos.'),
    N('El perro también, aunque nadie se lo ofreció.'),
    N('Y yo decidí que eso había sido trabajo en equipo de todas formas.'),
    N('Solo no lo dije en voz alta.'),
  ]},

{ lead:['El día del cabello.'],
  xml:'Mañana. Kenzo llega al río y encuentra a Hana diferente: la humedad rizó su cabello, siempre alisado, ahora ondulado. Completamente diferente.',
  set:'rio', light:'amanecer', season:'verano', opts:{tree:'sakura'},
  cast:[{who:'hana', pose:'curly', at:'center'}],
  lines:[
    N('Hubo una mañana que llegué al río y te encontré diferente.'),
    N('El cabello.'),
    N('La humedad del amanecer lo había arruinado, según tú.'),
    N('Según yo, era la primera vez que te veía así.'),
    N('Y me quedé parado un momento más de lo necesario.'),
  ]},

{ xml:'Hana lo nota parado. Lo mira.',
  set:'rio', light:'amanecer', season:'verano', opts:{tree:'sakura'},
  cast:[{who:'kenzo', pose:'stand', at:'left'}, {who:'hana', pose:'curly', at:'right'}],
  lines:[
    H('No digas nada.'),
    K('No dije nada.'),
    H('Estás a punto de decir algo.'),
    K('No estoy a punto de decir nada.'),
    K('Se te ve bien así.', '(pausa)'),
    H('Te pedí que no dijeras nada.', '(lo mira fijo)'),
    K('Dije algo bueno.'),
    H('No importa. Pedí que no dijeras nada.'),
    N('Se sentó con las hierbas y no volvió a tocar el tema.'),
    N('Yo tampoco. Pero sí seguí mirando.'),
    N('Y ella sabía que seguía mirando.'),
    N('Y ninguno dijo nada sobre eso tampoco.'),
  ]},

{ xml:'A mitad de la tarde, el cabello sigue igual. Hana saca un peine e intenta controlarlo. No funciona.',
  set:'rio', light:'tarde', season:'verano', opts:{tree:'sakura'},
  cast:[{who:'kenzo', pose:'sit', at:'left'}, {who:'hana', pose:'curly', at:'right'}], dog:{pos:'center', dx:0},
  lines:[
    N('A mitad de la tarde sacaste un peine.'),
    N('Y empezaste a tratar de controlarlo.'),
    N('No funcionó.'),
    K('Hana.'),
    H('No.', '(sin parar)'),
    K('Solo iba a decir—'),
    H('No.'),
    N('Seguiste peinando. El cabello siguió igual.'),
    N('Yo miré el río. Y sonreí solo.'),
    N('Que también aprendí a hacer sin que se notara.'),
  ]},

{ lead:['El viaje a Matsumoto.', 'Primera vez que salen de Kuromi juntos.'],
  xml:'Camino entre Kuromi y Matsumoto. Kenzo y Hana van a tomar la barca de pasajeros del río, el transporte común entre aldeas.',
  set:'camino', light:'amanecer', season:'verano', opts:{tree:'sakura'},
  cast:[{who:'kenzo', pose:'stand', at:'left'}, {who:'hana', pose:'stand', at:'right'}], dog:{pos:'center', dx:0},
  lines:[
    N('Un día tuve que ir a Matsumoto a buscar materiales para el taller.'),
    N('Le pregunté a Hana si quería venir.'),
    N('Dijo que sí antes de preguntar cómo íbamos a ir.'),
    N('Cuando le expliqué que íbamos en la barca de pasajeros del río, me miró como si hubiera dicho algo en otro idioma.'),
  ]},

{ xml:'En la barca, llena de gente y mercancía. Kenzo feliz, mira todo, habla con el barquero. Hana sentada muy derecha, el perro en sus piernas, procesando la cantidad de gente.',
  set:'barca', light:'dia', season:'verano', opts:{sun:true, tree:'sakura'},
  cast:[{who:'kenzo', pose:'sit', at:'left'}, {who:'hana', pose:'sit', at:'right'}],
  lines:[
    K('Mira eso.', '(señala algo en la orilla)'),
    H('¿Qué?', '(mirando hacia adelante, no hacia donde señala)'),
    K('El puente de piedra viejo. Dicen que lo construyeron hace doscientos años.'),
    H('Bien.'),
    K('¿Estás bien?'),
    H('Estoy bien.'),
    K('Hay mucha gente.'),
    H('Lo noto.'),
    K('¿Quieres que—?'),
    H('Estoy bien. Sigue con el puente.'),
    N('Seguí con el puente.'),
    N('Pero me acerqué un poco más.'),
    N('Para que hubiera menos espacio entre ella y la gente del otro lado.'),
    N('No lo mencioné. Ella tampoco.'),
  ]},

{ xml:'Llegando a Matsumoto: ciudad más grande, más ruido, más gente. Kenzo guiando con confianza. Hana siguiéndolo.',
  set:'matsumoto', light:'dia', season:'verano',
  cast:[{who:'kenzo', pose:'stand', at:'left'}, {who:'hana', pose:'stand', at:'right'}], dog:{pos:'center', dx:0},
  lines:[
    N('En Matsumoto yo era el guía.'),
    N('Lo cual era interesante porque yo tampoco conocía bien Matsumoto.'),
    N('Pero caminaba con confianza.'),
    N('Y Hana confiaba en la confianza.'),
    N('Que era una estrategia razonable hasta que dejó de serlo.'),
  ]},

{ xml:'Se pierden. Kenzo en una calle que no reconoce. Hana lo mira. Él mira alrededor con la misma confianza de antes.',
  set:'matsumoto', light:'dia', season:'verano',
  cast:[{who:'kenzo', pose:'stand', at:'left'}, {who:'hana', pose:'stand', at:'right'}],
  lines:[
    H('¿Sabes dónde estamos?'),
    K('Sí.'),
    H('¿Dónde?'),
    K('En Matsumoto.', '(pausa)'),
    H('...'),
    K('En la parte... este... sur. Creo.'),
    H('Kenzo.'),
    K('Dame un momento.'),
    N('Me dio el momento.'),
    N('El momento no resolvió nada.'),
  ]},

{ xml:'Hana suspira con resignación específica. Saca su lista, la revisa, mira alrededor con criterio analítico.',
  set:'matsumoto', light:'dia', season:'verano',
  cast:[{who:'kenzo', pose:'stand', at:'left'}, {who:'hana', pose:'stand', at:'right'}],
  lines:[
    H('El río está al norte. Si lo encontramos podemos orientarnos.'),
    K('¿Cómo sabes que el río está al norte?'),
    H('Porque llegamos por el río y veníamos del sur.'),
    K('Ah.'),
    H('¿No pensaste en eso?'),
    K('Estaba viendo el puente.'),
    N('No dijo nada. Empezó a caminar hacia el norte.'),
    N('Yo la seguí. El perro también.'),
    N('Sin preguntarle si sabía a dónde iba.'),
    N('Porque claramente sí sabía.'),
  ]},

{ xml:'Encuentran el río. Se orientan. Kenzo feliz aunque estuvieran perdidos. Hana suelta una risa pequeña, la primera que él le ve.',
  set:'rio', light:'tarde', season:'verano', opts:{sun:true, tree:'sakura'},
  cast:[{who:'kenzo', pose:'stand', at:'left'}, {who:'hana', pose:'stand', at:'right'}], dog:{pos:'center', dx:0},
  lines:[
    K('¿Ves? Lo encontramos.'),
    H('Tú no lo encontraste. Yo lo encontré.'),
    K('Íbamos juntos.'),
    H('Tú ibas detrás de mí.'),
    K('Como apoyo moral.'),
    N('Se detuvo. Me miró.'),
    N('Y soltó algo que nunca había visto.'),
    N('Una risa. Pequeña. Casi nada.'),
    N('Pero era una risa real. La primera que le vi.'),
    N('Y me pareció la cosa más importante que había visto en Matsumoto.'),
    N('Más que el puente de doscientos años.'),
  ]},

{ lead:['El mercado de Matsumoto.'],
  xml:'Mercado grande de Matsumoto, mucho más grande que el de Kuromi. Kenzo fascinado. Hana caminando más cerca de él que de costumbre.',
  set:'matsumoto', light:'dia', season:'verano',
  cast:[{who:'kenzo', pose:'stand', at:'left'}, {who:'hana', pose:'stand', at:'right'}],
  lines:[
    N('El mercado de Matsumoto era el doble que el de Kuromi.'),
    N('Para mí eso era fascinante.'),
    N('Para Hana era demasiada gente en demasiado poco espacio.'),
    N('Caminaba más cerca de mí que de costumbre.'),
    N('No lo dijo. Solo pasó.'),
  ]},

{ xml:'Puesto de especias enorme. Hana se detiene; sus ojos cambian — esto es su territorio. Empieza a revisar con criterio total.',
  set:'matsumoto', light:'dia', season:'verano',
  cast:[{who:'hana', pose:'hold', at:'center'}],
  lines:[
    N('Y entonces llegamos al puesto de especias.'),
    N('Y Hana dejó de estar incómoda.'),
    N('Y se convirtió en otra persona.'),
    N('O en la versión más completa de ella misma.'),
    N('Que era lo mismo.'),
  ]},

{ xml:'Hana huele, evalúa, compara. El vendedor le responde con respeto. Kenzo observa.',
  set:'matsumoto', light:'dia', season:'verano',
  cast:[{who:'kenzo', pose:'stand', at:'left'}, {who:'hana', pose:'hold', at:'right'}],
  lines:[
    K('Aquí sí eres feliz.', '(en voz baja, solo para él)'),
    H('No estaba siendo infeliz antes.', '(sin voltear)'),
    K('Pero aquí sí estás cómoda.'),
    H('Las especias están bien conservadas.', '(sigue con las especias)'),
    N('Lo traduje:'),
    N('Sí. Aquí sí estoy cómoda.'),
    N('Aprendí a hacer eso.'),
    N('Traducir lo que Hana decía a lo que Hana quería decir.'),
    N('Era casi un idioma.'),
  ]},

{ lead:['De regreso a Kuromi.', 'En la barca.', 'Tarde.'],
  xml:'La barca de regreso, menos gente. El sol bajando. Hana sentada, el perro dormido en sus piernas. Kenzo a su lado.',
  set:'barca', light:'atardecer', season:'verano',
  cast:[{who:'kenzo', pose:'sit', at:'left'}, {who:'hana', pose:'sit', at:'right'}],
  lines:[
    N('En la barca de vuelta había menos gente.'),
    N('Hana estaba más relajada.'),
    N('El perro dormía encima de ella.'),
    N('Y el río llevaba el color del atardecer.'),
    H('El río desde aquí se ve diferente que desde la orilla.'),
    K('Sí.'),
    H('Me gusta más desde aquí.', '(pausa)'),
    N('No dijiste nada más. Pero eso era mucho.'),
    N('Porque Hana no decía que algo le gustaba más si no era verdad.'),
    N('No tenía esa clase de cortesía.'),
    N('Si lo decía, era porque era verdad.'),
    N('Y lo había dicho sobre algo que yo amaba.'),
    N('Así que lo guardé. Como guardaba todo lo suyo.'),
  ]},

{ lead:['La discusión del puente.', 'Una tarde cualquiera.'],
  xml:'Las escaleras del templo. Hana terminó una figura — una garza. La examina, está bien, la deja entre los dos.',
  set:'templo', light:'tarde', season:'verano', opts:{night:false},
  cast:[{who:'kenzo', pose:'sit', at:'left'}, {who:'hana', pose:'sit', at:'right'}], dog:{pos:'right', dx:-30},
  lines:[
    N('Hubo una tarde que discutimos.'),
    N('Por algo sin importancia.'),
    N('Como pasa con las cosas que realmente importan.'),
    K('¿Por qué las organizas por tipo y no por cuándo las necesitas?'),
    H('Porque organizarlas por tipo tiene más sentido.'),
    K('Para ti.'),
    H('Para cualquiera que piense en ello.'),
    K('Yo las organizaría por uso.'),
    H('Y perderías tiempo buscando cuando se traslapan.'),
    K('No necesariamente.'),
    H('Sí necesariamente.'),
  ]},

{ xml:'Silencio. Los dos mirando en distintas direcciones. El perro los mira a uno y al otro. Kenzo suspira y cede.',
  set:'templo', light:'atardecer', season:'verano', opts:{night:false},
  cast:[{who:'kenzo', pose:'sit', at:'left'}, {who:'hana', pose:'sit', at:'right'}], dog:{pos:'center', dx:0},
  lines:[
    N('Nos quedamos callados un rato.'),
    N('Yo pensando si tenía razón.'),
    N('Ella probablemente confirmando que tenía razón.'),
    K('Está bien. Por tipo.'),
    H('No tienes que estar de acuerdo solo para terminar la discusión.', '(pausa)'),
    K('No lo hago solo para terminarla.'),
    H('¿No?'),
    K('Bueno. Sí un poco.'),
    N('Algo en tu cara cambió. Muy poco. Pero fue algo.'),
    N('Como si hubieras esperado que lo admitiera.'),
    N('Y que te gustara que lo hiciera.'),
    H('Por tipo es mejor.'),
    K('Probablemente.'),
    H('No probablemente.'),
    K('Definitivamente.', '(pausa)'),
    N('No era una victoria. Pero lo parecía un poco.'),
    N('Y ella lo dejó parecer. Que para Hana era mucho.'),
  ]},

{ lead:['El final del verano.', 'Las cosas que se forman sin decidirlas.'],
  xml:'Secuencia de momentos: el río, el templo, el camino. Los mismos lugares con el peso de meses acumulados. Las costumbres ya están ahí sin que nadie las declarara.',
  set:'rio', light:'tarde', season:'verano', opts:{sun:true, tree:'sakura'},
  cast:[{who:'kenzo', pose:'sit', at:'left'}, {who:'hana', pose:'sit', at:'right'}], dog:{pos:'center', dx:0},
  lines:[
    N('Al final del verano ya teníamos costumbres.'),
    N('No las habíamos decidido. Solo aparecieron.'),
    N('El río por las mañanas.'),
    N('Las escaleras del templo a veces.'),
    N('La comida que traía ella.'),
    N('Las cosas que construía yo.'),
    N('El perro que era de los dos aunque ninguno lo hubiera decidido así.'),
    N('Y los silencios que ya no necesitaban llenarse.'),
    N('Eso. Eso era lo que más valía.'),
  ]},

{ xml:'Noche. Kenzo en el techo del taller. La cajita abierta: la grulla, varias notas, la figura de la garza nueva.',
  set:'techo', light:'noche', season:'verano',
  cast:[{who:'kenzo', pose:'sit', at:'center'}], prop:'box',
  lines:[
    N('Esa noche abrí la cajita.'),
    N('Conté lo que había adentro.'),
    N('Notas. Figuras. Una lista de hierbas que me había dado para que aprendiera.'),
    N('La garza de esa tarde.'),
    N('Todo cuidadosamente doblado.'),
    N('Todo con los mismos dobleces de siempre.'),
    N('Porque si lo doblas diferente cada vez, al final no sabes dónde está lo importante.'),
    N('Cerré la caja.'),
    N('Y pensé que si había una manera de que esto siguiera siendo así para siempre, yo la quería encontrar.'),
    N('Sin saber todavía que el tiempo tenía sus propios planes.'),
    N('Y que los planes del tiempo no preguntan.'),
  ]},

/* ============================ CAPÍTULO 3 ============================
   "Lo que se dijo y lo que no alcanzó" */
{ chapter:'Capítulo 3', chapterName:'Lo que se dijo y lo que no alcanzó', chapterWhen:'Verano. Él dice lo que siente. Y la vida sigue de todas formas.',
  lead:['Verano.', 'Kenzo lleva meses guardando algo.', 'Hoy lo va a decir.'],
  xml:'El río. Tarde de verano calurosa. Los dos en su lugar de siempre, el perro dormido. El silencio de costumbre, pero Kenzo está diferente: más quieto, menos palabras.',
  set:'rio', light:'tarde', season:'verano', opts:{sun:true, tree:'sakura'},
  cast:[{who:'kenzo', pose:'sit', at:'left'}, {who:'hana', pose:'sit', at:'right'}], dog:{pos:'center', dx:0},
  lines:[
    N('Llevaba semanas con algo que no sabía cómo sacar.'),
    N('No era complicado.'),
    N('Era simple.'),
    N('Pero simple no significa fácil.'),
    N('Y yo que nunca me quedaba callado, de repente no encontraba por dónde empezar.'),
  ]},

{ xml:'Hana trabaja con sus hierbas. Lo mira de reojo una vez — nota que está callado más de lo normal. Regresa a sus hierbas sin decir nada.',
  set:'rio', light:'tarde', season:'verano', opts:{tree:'sakura'},
  cast:[{who:'kenzo', pose:'sit', at:'left'}, {who:'hana', pose:'sit', at:'right'}], dog:{pos:'center', dx:0},
  lines:[
    N('Me miraste.'),
    N('Notaste que algo estaba diferente.'),
    N('No preguntaste.'),
    N('Esperaste.'),
    N('Que también era tu manera.'),
  ]},

{ xml:'Kenzo mira el río. Respira. Se voltea hacia ella.',
  set:'rio', light:'tarde', season:'verano', opts:{tree:'sakura'},
  cast:[{who:'kenzo', pose:'sit', at:'left'}, {who:'hana', pose:'sit', at:'right'}], dog:{pos:'center', dx:0},
  lines:[
    K('Hana.'),
    H('¿Qué?', '(sin levantar la vista)'),
    K('Tengo que decirte algo.'),
    H('Dilo.', '(ahora sí lo mira)'),
    N('Así de directo.'),
    N('Dilo.'),
    N('Sin preámbulo.'),
    N('Sin prepararte.'),
    N('Solo: dilo.'),
    N('Que era exactamente lo que necesitaba escuchar.'),
  ]},

{ xml:'Kenzo la mira directo. Ella sostiene la mirada. El sol bajando. El perro abre un ojo y lo cierra.',
  set:'rio', light:'atardecer', season:'verano', opts:{tree:'sakura'},
  cast:[{who:'kenzo', pose:'sit', at:'left'}, {who:'hana', pose:'sit', at:'right'}], dog:{pos:'center', dx:0},
  lines:[
    K('Me gustas.'),
    K('Desde hace tiempo.'),
    K('No lo había dicho porque no sabía cómo, o porque me daba miedo, o las dos cosas.'),
    K('Pero ya no tiene sentido seguir sin decirlo.'),
    B('— el río · el perro que abre un ojo y lo cierra —'),
    H('Ah.'),
    N('Ah.'),
    N('Solo eso.'),
    N('Ah.'),
  ]},

{ xml:'Silencio. Hana mira sus manos. Luego el río. Kenzo la mira a ella. El sol bajando lento.',
  set:'rio', light:'atardecer', season:'verano', opts:{tree:'sakura'},
  cast:[{who:'kenzo', pose:'sit', at:'left'}, {who:'hana', pose:'sit', at:'right'}], dog:{pos:'center', dx:0},
  lines:[
    N('No dijiste nada más por un rato.'),
    N('Aprendí a esperar tus tiempos.'),
    N('Así que esperé.'),
    N('Esta vez fueron más de veinte pasos.'),
    N('Mucho más.'),
  ]},

{ xml:'Hana lo mira. Él sostiene la mirada. Ella abre la boca, la cierra, mira el agua otra vez.',
  set:'rio', light:'atardecer', season:'verano', opts:{tree:'sakura'},
  cast:[{who:'kenzo', pose:'sit', at:'left'}, {who:'hana', pose:'sit', at:'right'}], dog:{pos:'center', dx:0},
  lines:[
    H('No sé qué decirte.'),
    K('No tienes que decir nada ahorita.'),
    H('¿Estás seguro de lo que dices?', '(pausa larga)'),
    K('Sí.'),
    H('Okay.', '(otro momento)'),
    N('Okay.'),
    N('No era un sí.'),
    N('No era un no.'),
    N('Era ella siendo honesta sobre no saber todavía.'),
    N('Y yo lo respeté.'),
    N('Aunque no supiera bien qué hacer con eso.'),
  ]},

{ xml:'Los dos siguen en el río un rato más. El tema no vuelve. El silencio es diferente al de antes: no incómodo, pero cargado de algo nuevo.',
  set:'rio', light:'atardecer', season:'verano', opts:{tree:'sakura'},
  cast:[{who:'kenzo', pose:'sit', at:'left'}, {who:'hana', pose:'sit', at:'right'}], dog:{pos:'center', dx:0},
  lines:[
    N('Nos quedamos un rato más.'),
    N('No volvimos a hablar del tema.'),
    N('Pero el río ese día se sentía diferente.'),
    N('O yo me lo imaginé.'),
    N('Probablemente me lo imaginé.'),
  ]},

{ lead:['Las semanas siguientes.', 'Las cosas siguieron.', 'Y también cambiaron.'],
  xml:'El río, los días después. Todo casi igual, pero hay algo nuevo flotando entre los dos. No incómodo. Solo presente.',
  set:'rio', light:'dia', season:'verano', opts:{tree:'sakura', ducks:true},
  cast:[{who:'kenzo', pose:'sit', at:'left'}, {who:'hana', pose:'sit', at:'right'}], dog:{pos:'center', dx:0},
  lines:[
    N('Las cosas siguieron.'),
    N('El río. Las hierbas. La cajita con notas.'),
    N('Yo hablando. Tú escuchando.'),
    N('Pero ahora lo que había entre nosotros tenía nombre.'),
    N('Y los dos sabíamos que el otro lo sabía.'),
    N('Eso cambiaba algunas cosas.'),
    N('No todas.'),
    N('Pero sí algunas.'),
  ]},

{ xml:'Un momento específico — Kenzo dice algo, Hana lo mira diferente al usual. No mucho. Pero diferente. Él lo nota. No dice nada. Sigue hablando.',
  set:'rio', light:'dia', season:'verano', opts:{tree:'sakura'},
  cast:[{who:'kenzo', pose:'sit', at:'left'}, {who:'hana', pose:'sit', at:'right'}], dog:{pos:'center', dx:0},
  lines:[
    N('A veces te me quedabas viendo diferente.'),
    N('No mucho.'),
    N('Pero sí diferente al usual.'),
    N('Y yo fingía que no lo había notado.'),
    N('Y tú fingías que no lo habías hecho.'),
    N('Y así seguíamos.'),
    N('Que era un sistema raro.'),
    N('Pero era nuestro sistema.'),
  ]},

{ xml:'Un día Hana llega al río con algo preparado especialmente — no la comida de siempre, algo más elaborado. Lo pone entre los dos sin decir nada.',
  set:'rio', light:'tarde', season:'verano', opts:{sun:true, tree:'sakura'},
  cast:[{who:'kenzo', pose:'sit', at:'left'}, {who:'hana', pose:'sit', at:'right'}], dog:{pos:'center', dx:0},
  lines:[
    N('Un día llegaste con algo diferente.'),
    N('Más elaborado que lo de siempre.'),
    N('Sin decir por qué.'),
    N('Sin decir nada.'),
    N('Solo lo pusiste entre los dos.'),
  ]},

{ xml:'Kenzo lo prueba. Es muy bueno. Lo mira. La mira a ella. Ella está viendo el río.',
  set:'rio', light:'tarde', season:'verano', opts:{tree:'sakura'},
  cast:[{who:'kenzo', pose:'sit', at:'left'}, {who:'hana', pose:'sit', at:'right'}],
  lines:[
    K('Hana.'),
    H('¿Qué?'),
    K('Esto está muy bien hecho.'),
    H('Lo sé.', '(sin voltear)'),
    K('Específicamente: el balance entre los sabores es exacto. No sobra nada.'),
    H('Bien.', '(un momento)'),
    N('Bien.'),
    N('Que de parte de ella era bastante.'),
    N('Lo guardé.'),
    N('Como guardaba todo lo suyo.'),
  ]},

{ lead:['Final del verano.', 'Algo empieza a cambiar.', 'Sin que nadie lo diga.'],
  xml:'El grupo de arquería del templo practicando en el patio exterior. Kenzo pasa por ahí por casualidad. Ve a Hana entre el grupo — concentrada, en su elemento, más suelta, más parte de algo.',
  set:'arqueria', light:'tarde', season:'verano', opts:{sun:true, tree:'sakura'},
  cast:[{who:'hana', pose:'bow', at:'center'}],
  lines:[
    N('Una tarde pasé por el templo y la vi practicando con su grupo.'),
    N('Arquería.'),
    N('Llevaba años en ese grupo.'),
    N('Desde antes de llegar a Kuromi.'),
    N('Y se le notaba.'),
    N('Se movía diferente ahí.'),
    N('Más suelta.'),
    N('Más parte de algo que tenía historia antes que yo.'),
  ]},

{ xml:'Kenzo la observa desde afuera sin entrar. Después de la práctica, Hana habla con otros del grupo con naturalidad y confianza.',
  set:'arqueria', light:'atardecer', season:'verano', opts:{tree:'sakura'},
  cast:[{who:'kenzo', pose:'stand', at:'left', dim:true, w:'42%'}, {who:'hana', pose:'stand', at:'right'}],
  lines:[
    N('Tenías un mundo antes de mí.'),
    N('Lo sabía.'),
    N('Pero ese día lo vi.'),
    N('Y entendí que ese mundo tenía sus propias personas, sus propios lazos.'),
    N('Formados con años.'),
    N('Yo tenía un verano.'),
    N('No más que eso.'),
  ]},

{ lead:['Otoño llegando.', 'La noticia llega al taller.'],
  xml:'Interior del taller. El padre de Kenzo hablando con él — algo serio, importante. Kenzo escuchando; su cara cambia mientras escucha.',
  set:'taller', light:'dia', season:'otono',
  cast:[{who:'padre', pose:'work', at:'right'}, {who:'kenzo', pose:'stand', at:'left'}],
  lines:[
    N('En otoño mi padre me dijo algo que no esperaba.'),
    N('Un maestro artesano de Matsumoto estaba buscando aprendices.'),
    N('Alguien había recomendado mi trabajo.'),
    N('Era una oportunidad real.'),
    N('Dos años en la ciudad aprendiendo el oficio en serio.'),
    N('Mi padre no lo dijo como pregunta.'),
    N('Lo dijo como algo que iba a pasar.'),
  ]},

{ xml:'Kenzo solo esa noche en el techo del taller, mirando las estrellas. La noticia todavía asentándose.',
  set:'techo', light:'noche', season:'otono',
  cast:[{who:'kenzo', pose:'sit', at:'center'}],
  lines:[
    N('Esa noche no dormí bien.'),
    N('Pensé en Matsumoto.'),
    N('En dos años.'),
    N('En lo que eso significaba.'),
    N('Y pensé en el río.'),
    N('Y en Hana.'),
    N('Y en que todavía no había pasado nada concreto entre los dos.'),
    N('Solo un okay que no era sí ni no.'),
    N('Y yo que me iba en unos meses.'),
  ]},

{ xml:'El río. Kenzo llega. Hana ya está. Todo como siempre. Él se sienta. El perro lo saluda.',
  set:'rio', light:'tarde', season:'otono', opts:{tree:'otono', hill:'#8a7a4a', frontBank:'#a8985a'},
  cast:[{who:'kenzo', pose:'sit', at:'left'}, {who:'hana', pose:'sit', at:'right'}], dog:{pos:'center', dx:0},
  lines:[
    N('Fui al río al día siguiente.'),
    N('Con la noticia encima.'),
    N('No supe cómo decírtela.'),
    N('Así que primero no dije nada.'),
    N('Solo estuve ahí un rato.'),
  ]},

{ xml:'Kenzo finalmente lo dice. Hana deja de trabajar con las hierbas. Lo mira.',
  set:'rio', light:'tarde', season:'otono', opts:{tree:'otono', hill:'#8a7a4a', frontBank:'#a8985a'},
  cast:[{who:'kenzo', pose:'sit', at:'left'}, {who:'hana', pose:'sit', at:'right'}], dog:{pos:'center', dx:0},
  lines:[
    K('Me voy a Matsumoto en dos meses.'),
    H('¿A Matsumoto?'),
    K('Dos años de aprendiz con un maestro artesano.'),
    B('— silencio —'),
    H('¿Cuándo supiste?'),
    K('Ayer.'),
    B('— silencio más largo —'),
    H('Bien.'),
    N('Esta vez el bien sí pesó diferente.'),
    N('No era el bien de cuando la comida estaba bien hecha.'),
    N('Era otro bien.'),
    N('El que usas cuando no sabes qué más decir.'),
  ]},

{ xml:'Los dos en silencio. El río corriendo. El verano terminando. Las primeras hojas cambiando de color al fondo.',
  set:'rio', light:'atardecer', season:'otono', opts:{tree:'otono', hill:'#8a7a4a', frontBank:'#a8985a'},
  cast:[{who:'kenzo', pose:'sit', at:'left'}, {who:'hana', pose:'sit', at:'right'}], dog:{pos:'center', dx:0},
  lines:[
    N('No hablamos mucho más ese día.'),
    N('Nos quedamos hasta que oscureció.'),
    N('Sin decirlo.'),
    N('Solo nos quedamos.'),
  ]},

{ lead:['Los dos meses siguientes.', 'Todo igual.', 'Y con fecha.'],
  xml:'El río, el templo, el camino. Los mismos lugares. Pero ahora hay un reloj encima de todo. Kenzo lo siente en cada tarde.',
  set:'camino', light:'tarde', season:'otono', opts:{tree:'otono'},
  cast:[{who:'kenzo', pose:'stand', at:'left'}, {who:'hana', pose:'stand', at:'right'}], dog:{pos:'center', dx:0},
  lines:[
    N('Esos dos meses fueron raros.'),
    N('Todo igual que antes.'),
    N('El río. Las hierbas. La comida. Las notas.'),
    N('Pero con fecha.'),
    N('Y cuando las cosas tienen fecha, pesan diferente.'),
  ]},

{ xml:'Una tarde. Kenzo llega con algo que hizo en el taller, más elaborado que la cajita: un porta-notas de madera con compartimento escondido para papeles doblados. Lo trabajó semanas.',
  set:'rio', light:'tarde', season:'otono', opts:{tree:'otono', hill:'#8a7a4a', frontBank:'#a8985a'},
  cast:[{who:'kenzo', pose:'sit', at:'left'}, {who:'hana', pose:'sit', at:'right'}], prop:'portanotas',
  lines:[
    N('Hice algo en el taller esas semanas.'),
    N('Lo pensé mucho.'),
    N('Un porta-notas de madera.'),
    N('Con un compartimento adentro para guardar papeles doblados.'),
    N('Encajaba perfectamente.'),
    N('Sin holgura.'),
    N('Porque sabía que eso era lo que más te importaba.'),
    N('Que las cosas cerraran bien.'),
  ]},

{ xml:'Kenzo se lo da a Hana en el río. Ella lo recibe y lo examina con su criterio de siempre, pero más lento, más cuidadoso.',
  set:'rio', light:'tarde', season:'otono', opts:{tree:'otono', hill:'#8a7a4a', frontBank:'#a8985a'},
  cast:[{who:'kenzo', pose:'sit', at:'left'}, {who:'hana', pose:'sit', at:'right'}], prop:'portanotas',
  lines:[
    N('Lo examinaste como examinabas todo.'),
    N('Pero más despacio que de costumbre.'),
    N('Abriste el compartimento.'),
    N('Pusiste un papel doblado adentro.'),
    N('Cerró perfectamente.'),
  ]},

{ xml:'Hana lo mira a él, no al porta-notas. A él. Un momento largo.',
  set:'rio', light:'atardecer', season:'otono', opts:{tree:'otono', hill:'#8a7a4a', frontBank:'#a8985a'},
  cast:[{who:'kenzo', pose:'sit', at:'left'}, {who:'hana', pose:'sit', at:'right'}],
  lines:[
    H('¿Por qué esto?'),
    K('Para que tengas dónde guardar las notas.'),
    H('Ya tengo la cajita.', '(pausa)'),
    K('Esa se la quedé yo.'),
    N('No dijiste nada más.'),
    N('Guardaste el porta-notas en tu bolsa.'),
    N('Y yo supe que lo ibas a usar.'),
    N('Porque no guardabas cosas que no ibas a usar.'),
  ]},

{ lead:['La última semana.'],
  xml:'El río. Tarde. Los dos como siempre. Pero ya es la última semana. Los dos lo saben. Ninguno lo dice.',
  set:'rio', light:'tarde', season:'otono', opts:{sun:true, tree:'otono', hill:'#8a7a4a', frontBank:'#a8985a'},
  cast:[{who:'kenzo', pose:'sit', at:'left'}, {who:'hana', pose:'sit', at:'right'}], dog:{pos:'center', dx:0},
  lines:[
    N('La última semana antes de irme fue la más larga.'),
    N('Íbamos al río como siempre.'),
    N('Hablábamos como siempre.'),
    N('Pero había algo debajo de todo que los dos sentíamos.'),
    N('Y que ninguno nombraba.'),
  ]},

{ xml:'Penúltimo día. El río. Hana le da un papel doblado, sacado del porta-notas que él le hizo. Se lo da directamente esta vez.',
  set:'rio', light:'tarde', season:'otono', opts:{tree:'otono', hill:'#8a7a4a', frontBank:'#a8985a'},
  cast:[{who:'kenzo', pose:'sit', at:'left'}, {who:'hana', pose:'sit', at:'right'}], prop:'note',
  lines:[
    N('El penúltimo día me diste un papel.'),
    N('Directamente.'),
    N('No lo dejaste en algún lugar para que lo encontrara.'),
    N('Me lo diste en la mano.'),
    N('Sin mirarme mientras lo hacías.'),
    N('Como siempre.'),
  ]},

{ xml:'Kenzo toma el papel. La mira.',
  set:'rio', light:'atardecer', season:'otono', opts:{tree:'otono', hill:'#8a7a4a', frontBank:'#a8985a'},
  cast:[{who:'kenzo', pose:'sit', at:'left'}, {who:'hana', pose:'sit', at:'right'}],
  lines:[
    K('¿Lo leo ahorita?'),
    H('Cuando quieras.', '(un momento)'),
    N('Esta vez no dijo: léelo después.'),
    N('Dijo: cuando quieras.'),
    N('Eso era diferente.'),
  ]},

{ xml:'Kenzo abre el papel y lo lee. No vemos el contenido, solo su cara: primero atento, luego algo más suave.',
  set:'rio', light:'atardecer', season:'otono', opts:{tree:'otono', hill:'#8a7a4a', frontBank:'#a8985a'},
  cast:[{who:'kenzo', pose:'sit', at:'center'}], prop:'note',
  lines:[
    N('Lo leí ahí mismo.'),
    N('Con ella presente.'),
    N('No decía mucho.'),
    N('Nunca decías mucho.'),
    N('Pero decía que el río iba a ser más aburrido sin alguien que no sabe distinguir las hierbas.'),
    N('Y que esperaba que Matsumoto tuviera mejores especias que Kuromi.'),
    N('Y al final, muy pequeño:'),
    N('Cuídate.'),
    N('Dos palabras.'),
    N('Pero venían de Hana.'),
    N('Y de Hana dos palabras valían bastante.'),
  ]},

{ xml:'Kenzo dobla el papel y lo guarda en la cajita — la que ella le había devuelto con la grulla.',
  set:'rio', light:'atardecer', season:'otono', opts:{tree:'otono', hill:'#8a7a4a', frontBank:'#a8985a'},
  cast:[{who:'kenzo', pose:'sit', at:'left'}, {who:'hana', pose:'sit', at:'right'}], prop:'cajita',
  lines:[
    K('Voy a volver.'),
    H('Lo sé.', '(mira el río)'),
    K('Y cuando vuelva, quiero que—'),
    H('No.', '(lo detiene, suave)'),
    K('Ni siquiera sabes qué iba a decir.'),
    H('Sí sé. Y no me prometas nada que todavía no sepas si vas a poder cumplir.', '(pausa)'),
    N('No lo dijo para alejarme.'),
    N('Lo dijo porque Hana no hacía promesas que no pudiera garantizar.'),
    N('Ni siquiera me dejaba hacerlas a mí.'),
    K('¿Entonces?'),
    H('Cuando vuelvas, vemos.', '(silencio largo)'),
    N('Cuando vuelvas, vemos.'),
    N('No era una promesa.'),
    N('No era un cierre.'),
    N('Era Hana siendo honesta sobre no saber el futuro.'),
    N('Que siempre era mejor que una promesa vacía.'),
    N('Lo entendí. Lo respeté.'),
    N('Y también me pesó.'),
  ]},

{ xml:'Último día. Kenzo en el camino que sale de Kuromi, mochila al hombro. El taller atrás, la aldea atrás. El río invisible desde ahí pero presente.',
  set:'camino', light:'amanecer', season:'otono', opts:{tree:'otono'},
  cast:[{who:'kenzo', pose:'bag', at:'center'}],
  lines:[
    N('Me fui un martes de otoño.'),
    N('No nos despedimos en el río.'),
    N('No quise.'),
    N('El río era nuestro lugar.'),
    N('No quería que la última imagen fuera una despedida ahí.'),
    N('Así que solo me fui.'),
    N('Con la cajita en la mochila.'),
  ]},

{ xml:'A mitad del camino a Matsumoto, Kenzo se detiene y abre la cajita para revisar que todo estuviera. Sobre el papel nuevo hay una figura de papel que él no puso. Hana la dejó, sin decir nada.',
  set:'camino', light:'dia', season:'otono', opts:{tree:'otono'},
  cast:[{who:'kenzo', pose:'sit', at:'center'}], prop:'crane',
  lines:[
    N('A mitad del camino abrí la cajita.'),
    N('Solo para revisar que todo estuviera.'),
    N('El papel nuevo seguía adentro.'),
    N('Pero había algo más.'),
    N('Una figura.'),
    N('Una que yo no había puesto.'),
    N('Doblada con los mismos dobleces de siempre.'),
    N('No era una nota.'),
    N('No hacía falta.'),
    N('La dejaste sin decir nada.'),
    N('Como dejabas las cosas que más pesaban.'),
    N('La guardé con cuidado en la cajita.'),
    N('Y seguí caminando a Matsumoto.'),
    N('Un poco menos solo de lo que pensé que iba a estar.'),
  ]},
/* ============================ CAPÍTULO 4 ============================
   "Lo que el tiempo hace cuando uno no mira" */
{ chapter:'Capítulo 4', chapterName:'Lo que el tiempo hace cuando uno no mira', chapterWhen:'Matsumoto. Dos años. Y lo que pasó en Kuromi sin él.',
  lead:['Matsumoto.', 'A un día de camino de Kuromi.', 'Año 1803.'],
  xml:'Matsumoto, ciudad más grande que Kuromi. Kenzo llegando con su mochila, mirando alrededor. El taller del maestro al fondo de una calle angosta.',
  set:'matsumoto', light:'dia', season:'otono',
  cast:[{who:'kenzo', pose:'bag', at:'center'}],
  lines:[
    N('Matsumoto era diferente a todo lo que conocía.'),
    N('Más ruido. Más gente. Más especias en el mercado.'),
    N('Lo primero que pensé cuando vi el puesto de especias fue: Hana tendría mucho que decir sobre esto.'),
    N('Eso me dijo que iba a ser un viaje largo.'),
  ]},

{ xml:'El taller del maestro Hiroshi: ordenado, preciso, maderas en las paredes. El maestro, hombre mayor de pocas palabras, revisando el trabajo de Kenzo el primer día sin decir nada.',
  set:'taller', light:'dia', season:'otono',
  cast:[{who:'maestro', pose:'stand', at:'right'}, {who:'kenzo', pose:'stand', at:'left'}],
  lines:[
    N('El maestro se llamaba Hiroshi.'),
    N('Era del tipo de personas que no dice más de lo necesario.'),
    N('El primer día revisó lo que sabía hacer.'),
    N('No dijo si estaba bien o mal.'),
    N('Solo señaló lo siguiente que debía aprender.'),
    N('Aprendí que eso significaba que había pasado la prueba.'),
    N('Me recordó a alguien.'),
  ]},

{ xml:'Kenzo trabajando en el taller los primeros meses. Cometiendo errores. Corrigiéndolos. Aprendiendo despacio.',
  set:'taller', light:'dia', season:'invierno',
  cast:[{who:'kenzo', pose:'sit', at:'center'}], prop:'trampa',
  lines:[
    N('Los primeros meses fueron difíciles.'),
    N('Creía que sabía bastante de carpintería.'),
    N('No sabía nada.'),
    N('O más bien: sabía lo suficiente para Kuromi.'),
    N('No lo suficiente para este taller.'),
    N('Hiroshi no me lo dijo con palabras.'),
    N('Me lo dijo con trabajo.'),
    N('Que es la manera más honesta.'),
  ]},

{ lead:['Primera semana.', 'Primera carta.'],
  xml:'Kenzo en su cuarto pequeño en Matsumoto. Escribe una nota con sus dobleces torcidos de siempre. La manda.',
  set:'cuarto', light:'noche', season:'invierno',
  cast:[{who:'kenzo', pose:'sit', at:'center'}], prop:'note',
  lines:[
    N('La primera semana le mandé una nota.'),
    N('Le conté sobre el taller.'),
    N('Sobre Matsumoto.'),
    N('Sobre el puesto de especias que era el doble que el de Kuromi.'),
    N('Y que probablemente ella tendría mucho que decir al respecto.'),
    N('Intenté doblarla bien.'),
    N('No quedó igual que las suyas.'),
    N('Nunca quedaba igual.'),
    N('La mandé de todas formas.'),
  ]},

{ xml:'Días después llega la respuesta. Kenzo la reconoce antes de abrirla por los dobleces perfectos.',
  set:'cuarto', light:'noche', season:'invierno',
  cast:[{who:'kenzo', pose:'sit', at:'center'}], prop:'note',
  lines:[
    N('Respondió rápido.'),
    N('La reconocí antes de abrirla.'),
    N('Los dobleces. Siempre los mismos dobleces.'),
    N('Decía que el perro había roto algo en la cocina.'),
    N('Que el señor Mori había recibido especias nuevas pero seguían mal conservadas.'),
    N('Y al final: espero que el trabajo vaya bien.'),
    N('Cuatro palabras al final.'),
    N('Que de parte de Hana eran un párrafo completo.'),
  ]},

{ lead:['Las semanas siguientes.', 'Las notas funcionan.'],
  xml:'Notas yendo y viniendo, semanales. Las de Hana perfectamente dobladas, las de él mejorando pero nunca iguales.',
  set:'cuarto', light:'noche', season:'invierno',
  cast:[{who:'kenzo', pose:'sit', at:'center'}], prop:'box',
  lines:[
    N('Las notas iban y venían cada semana.'),
    N('Las suyas siempre perfectamente dobladas.'),
    N('Las mías mejorando con el tiempo.'),
    N('Nunca iguales a las suyas.'),
    N('Pero ella nunca lo mencionó.'),
    N('Le contaba del taller.'),
    N('Ella me contaba de las hierbas. Del perro. Del grupo de arquería.'),
    N('Cosas pequeñas.'),
    N('Pero suficientes para que Kuromi siguiera sintiéndose cerca.'),
  ]},

{ lead:['Tres meses después.'],
  xml:'Kenzo en el mercado de Matsumoto, en el puesto de especias. Las huele — todavía no distingue bien, pero intenta.',
  set:'matsumoto', light:'dia', season:'primavera',
  cast:[{who:'kenzo', pose:'stand', at:'center'}],
  lines:[
    N('Una tarde me puse a oler especias en el mercado.'),
    N('El vendedor me miraba como el señor Mori miraba a Hana el primer día.'),
    N('Confundido.'),
    N('No pude distinguir cuáles estaban bien conservadas.'),
    N('Pero las olí.'),
    N('Se lo conté en la siguiente nota.'),
    N('Su respuesta fue: la nariz necesita práctica igual que las manos.'),
    N('Tres palabras de instrucción.'),
    N('Disfrazadas de observación. Como siempre.'),
  ]},

{ lead:['Cuatro meses.', 'Cinco meses.', 'Seis meses.'],
  xml:'El tiempo pasando. Kenzo en el taller, mejorando. Las notas siguen, pero el tiempo entre cada una empieza a estirarse.',
  set:'taller', light:'dia', season:'verano',
  cast:[{who:'kenzo', pose:'sit', at:'center'}],
  lines:[
    N('A los seis meses, las notas seguían.'),
    N('Pero el tiempo entre una y otra empezó a estirarse.'),
    N('Antes era una semana.'),
    N('Ahora era diez días.'),
    N('A veces doce.'),
    N('No lo mencioné.'),
    N('Hana tenía su vida. Las hierbas. El estudio. El grupo de arquería.'),
    N('No iba a contarle los días.'),
    N('Pero los conté.'),
  ]},

{ lead:['Siete meses.'],
  xml:'Kenzo recibe una nota más corta que las anteriores. Le cuenta sobre un torneo de arquería, sobre el perro. Nada al final.',
  set:'cuarto', light:'noche', season:'verano',
  cast:[{who:'kenzo', pose:'sit', at:'center'}], prop:'note',
  lines:[
    N('La nota de los siete meses fue más corta.'),
    N('No mucho. Pero sí.'),
    N('Me contó sobre un torneo de arquería.'),
    N('Sobre el perro.'),
    N('Y nada al final.'),
    N('Sin el espero que el trabajo vaya bien.'),
    N('Que siempre estaba al final.'),
    N('Esta vez no.'),
    N('No le di demasiado peso.'),
    N('O eso intenté.'),
  ]},

{ lead:['Ocho meses.'],
  xml:'Kenzo manda su nota. Espera dos, tres semanas. Llega una respuesta breve, funcional.',
  set:'cuarto', light:'noche', season:'otono',
  cast:[{who:'kenzo', pose:'sit', at:'center'}], prop:'note',
  lines:[
    N('Esperé tres semanas la respuesta de los ocho meses.'),
    N('Cuando llegó, era corta.'),
    N('Me decía que las hierbas de otoño habían sido buenas este año.'),
    N('Que el perro seguía igual.'),
    N('Eso era todo.'),
    N('No pregunté por qué había tardado.'),
    N('No era mi lugar preguntar.'),
    N('Pero lo noté.'),
  ]},

{ lead:['Nueve meses.', 'Diez meses.'],
  xml:'Las notas espaciándose más. Kenzo más hábil en el taller. De noche, revisando la cajita: las notas de Hana, cada vez menos.',
  set:'cuarto', light:'noche', season:'invierno',
  cast:[{who:'kenzo', pose:'sit', at:'center'}], prop:'box',
  lines:[
    N('Las notas siguieron.'),
    N('Pero algo en ellas había cambiado.'),
    N('No en el tono. En la cantidad.'),
    N('Antes me contaba tres o cuatro cosas por nota.'),
    N('Ahora me contaba una. A veces dos.'),
    N('Y el tiempo entre cada una seguía estirándose.'),
    N('Yo seguía respondiendo con el mismo ritmo de siempre.'),
    N('Como si eso pudiera mantener algo.'),
    N('No podía. Pero lo intenté.'),
  ]},

{ lead:['Once meses.'],
  xml:'Kenzo escribe una nota más larga de lo usual, tratando de llenar el espacio con palabras. La respuesta llega corta: solo la pregunta de las hierbas.',
  set:'cuarto', light:'noche', season:'invierno',
  cast:[{who:'kenzo', pose:'sit', at:'center'}], prop:'note',
  lines:[
    N('En la nota de los once meses escribí más de lo usual.'),
    N('Le conté todo lo que había pasado en el taller.'),
    N('Una historia sobre Hiroshi que me pareció que le iba a gustar.'),
    N('Una pregunta sobre las hierbas de invierno. Otra sobre el perro.'),
    N('Llenando espacio con palabras.'),
    N('Que era lo que siempre hacía cuando algo me preocupaba.'),
    N('Llenar el espacio.'),
    N('Respondió la pregunta de las hierbas.'),
    N('Nada más.'),
    N('No mencionó la historia de Hiroshi. No mencionó al perro.'),
    N('Solo las hierbas. Precisa. Como siempre.'),
    N('Solo que antes la precisión venía con más.'),
    N('Y ahora venía sola.'),
  ]},

{ lead:['Un año.'],
  xml:'Kenzo en el taller. Hiroshi lo mira trabajar y asiente levemente — el trabajo ha mejorado mucho. Kenzo debería estar contento; está pensando en otra cosa.',
  set:'taller', light:'dia', season:'primavera',
  cast:[{who:'maestro', pose:'stand', at:'right'}, {who:'kenzo', pose:'sit', at:'left'}],
  lines:[
    N('Al año, Hiroshi me dijo que mi trabajo había mejorado considerablemente.'),
    N('De parte de Hiroshi eso era un elogio importante.'),
    N('Debería haberme importado más de lo que me importó ese día.'),
    N('Pero esa semana había mandado una nota.'),
    N('Y no había llegado respuesta.'),
    N('Y llevaba esperando doce días.'),
  ]},

{ lead:['Trece meses.'],
  xml:'La respuesta llega más de un mes después. Kenzo la abre despacio.',
  set:'cuarto', light:'noche', season:'primavera',
  cast:[{who:'kenzo', pose:'sit', at:'center'}], prop:'note',
  lines:[
    N('Llegó a los treinta y siete días.'),
    N('La abrí despacio.'),
    N('Decía que las hierbas de invierno habían sido difíciles de conseguir este año.'),
    N('Que el perro había aprendido a abrir la puerta de la cocina.'),
    N('Y al final, una línea:'),
    N('Espero que estés bien.'),
    N('No: espero que el trabajo vaya bien.'),
    N('Espero que estés bien.'),
    N('Era diferente.'),
    N('No supe si era mejor o peor.'),
    N('Pero era diferente.'),
  ]},

{ lead:['Catorce meses.', 'Quince meses.'],
  xml:'Las notas ahora son mensuales. Kenzo las manda puntuales. Las respuestas llegan cuando llegan, cada vez más cortas.',
  set:'cuarto', light:'noche', season:'verano',
  cast:[{who:'kenzo', pose:'sit', at:'center'}], prop:'box',
  lines:[
    N('Las notas se volvieron mensuales.'),
    N('Yo las mandaba puntuales.'),
    N('Las respuestas llegaban cuando llegaban.'),
    N('Y eran más cortas. No frías. Solo cortas.'),
    N('Como cuando alguien tiene menos que contarte.'),
    N('No porque no quiera.'),
    N('Sino porque sus días se están llenando con otras cosas.'),
    N('Y esas otras cosas no te incluyen a ti.'),
    N('Y nadie tiene la culpa de eso.'),
    N('Pero duele igual.'),
  ]},

{ lead:['Dieciséis meses.'],
  xml:'Kenzo en el mercado de Matsumoto. Se cruza con Daisuke, un conocido de Kuromi que viaja por trabajo. Se saludan, hablan.',
  set:'matsumoto', light:'dia', season:'otono',
  cast:[{who:'kenzo', pose:'stand', at:'left'}, {who:'daisuke', pose:'stand', at:'right'}],
  lines:[
    N('Un día me crucé con Daisuke.'),
    N('Era de Kuromi.'),
    N('Pasaba por Matsumoto en un viaje de comercio.'),
    N('Me alegré de verlo. Hablamos un rato.'),
    N('Me contó cosas de la aldea.'),
    N('El señor Tanaka había cerrado el puesto.'),
    N('Habían arreglado el camino al norte.'),
    N('Y entonces, de pasada, sin darle peso:'),
  ]},

{ xml:'Daisuke habla. Kenzo escucha. Su cara no cambia.',
  set:'matsumoto', light:'dia', season:'otono',
  cast:[{who:'kenzo', pose:'stand', at:'left'}, {who:'daisuke', pose:'stand', at:'right'}],
  lines:[
    {s:'Daisuke', t:'¿Sabes que Hana anda con alguien del grupo de arquería?'},
    K('No sabía.'),
    {s:'Daisuke', t:'Hiro. El hijo del herrero. Buen muchacho.'},
    K('Bien.'),
    {s:'Daisuke', t:'¿Lo conoces?'},
    K('De vista.'),
    N('Seguimos hablando.'),
    N('Pregunté por otras cosas. Me despedí bien.'),
    N('Y cuando Daisuke se fue me quedé parado en el mercado.'),
    N('Con el ruido de Matsumoto alrededor.'),
    N('Y pensé: Hiro. El hijo del herrero.'),
    N('Alguien del grupo de arquería.'),
    N('Alguien que estaba ahí cuando yo no estaba.'),
    N('Alguien que había estado siempre.'),
  ]},

{ xml:'Kenzo sigue caminando por el mercado. Pasa por el puesto de especias. Se detiene. Las mira.',
  set:'matsumoto', light:'tarde', season:'otono',
  cast:[{who:'kenzo', pose:'stand', at:'center'}],
  lines:[
    N('Pasé por el puesto de especias.'),
    N('Me detuve.'),
    N('No las olí.'),
    N('Solo las miré un momento.'),
    N('Y seguí caminando.'),
  ]},

{ xml:'Noche. Kenzo en su cuarto. La cajita abierta, todas las notas de Hana adentro. Las cuenta: las primeras largas, las últimas breves. Todas perfectamente dobladas.',
  set:'cuarto', light:'noche', season:'otono',
  cast:[{who:'kenzo', pose:'sit', at:'center'}], prop:'box',
  lines:[
    N('Esa noche abrí la cajita.'),
    N('Saqué todas las notas.'),
    N('Las de los primeros meses eran largas. Tres, cuatro cosas contadas.'),
    N('Las últimas tenían una. A veces dos.'),
    N('Todas perfectamente dobladas. Hasta las últimas.'),
    N('Eso también era ella.'),
    N('Que las cosas se acortaran no significaba que se hicieran con menos cuidado.'),
    N('Solo significaba que había menos que decir.'),
    N('Y Hana nunca decía más de lo que tenía.'),
  ]},

{ xml:'Kenzo con la grulla en la mano — la primera que Hana le dio, la que siempre estaba arriba de todo.',
  set:'cuarto', light:'noche', season:'otono',
  cast:[{who:'kenzo', pose:'sit', at:'center'}], prop:'crane',
  lines:[
    N('No estaba enojado con ella. No podía.'),
    N('Ella me había dicho cuando vuelvas, vemos.'),
    N('No me había prometido nada más.'),
    N('Y yo me había ido dos años.'),
    N('La vida no espera dos años.'),
    N('Especialmente no cuando uno no le da razones concretas para esperar.'),
    N('Yo le di un cuando vuelvas, vemos.'),
    N('Y la vida de Hana siguió. Como debía seguir.'),
    N('No te reemplazó. Continuó.'),
    N('Y eso es mucho más difícil de resolver.'),
    N('Porque no hay nadie a quien culpar.'),
    N('Solo el tiempo.'),
    N('Y el tiempo no escucha.'),
  ]},

{ lead:['El segundo año.', 'Kenzo trabaja. Aprende.', 'No manda más notas.'],
  xml:'El taller. Kenzo trabajando, más hábil, más formado. Su trabajo es notablemente mejor. De noche, la cajita cerrada.',
  set:'taller', light:'dia', season:'invierno',
  cast:[{who:'kenzo', pose:'sit', at:'center'}], prop:'portanotas',
  lines:[
    N('Dejé de mandar notas.'),
    N('No de golpe. Fui espaciándolas.'),
    N('Una al mes. Una cada dos meses.'),
    N('Y luego nada.'),
    N('No porque estuviera enojado.'),
    N('Sino porque ya no sabía qué decir que tuviera sentido mandarlo.'),
    N('Y Hana tampoco mandó más.'),
    N('Y ninguno lo mencionó.'),
    N('Y así fue.'),
  ]},

{ xml:'Kenzo frente al puesto de especias de Matsumoto. Esta vez sí las huele. Distingue algunas mal conservadas. Lo sabe — nadie se lo dice.',
  set:'matsumoto', light:'dia', season:'primavera',
  cast:[{who:'kenzo', pose:'stand', at:'center'}],
  lines:[
    N('Un día distinguí tres especias mal conservadas en el mercado.'),
    N('Sin que nadie me lo dijera. Solo lo supe.'),
    N('Me reí solo caminando de vuelta al taller.'),
    N('Pensando en quién me enseñó a notar eso.'),
    N('Sin saber que me lo estaba enseñando.'),
    N('Así funcionaba con ella.'),
    N('Te dejaba cosas sin decirte que te las estaba dejando.'),
  ]},

{ lead:['Último mes en Matsumoto.'],
  xml:'Hiroshi le da a Kenzo un formón de madera de cerezo el último día en el taller. Un gesto sobrio, significativo.',
  set:'taller', light:'dia', season:'primavera',
  cast:[{who:'maestro', pose:'stand', at:'right'}, {who:'kenzo', pose:'stand', at:'left'}],
  lines:[
    N('El último día, Hiroshi me dio un formón de cerezo.'),
    N('No dijo nada cuando me lo dio.'),
    N('Solo me lo puso en la mano.'),
    N('Que de parte de Hiroshi era un discurso completo.'),
    N('Guardé el formón en la mochila.'),
    N('Al lado de la cajita.'),
    N('Y al día siguiente tomé el camino de vuelta a Kuromi.'),
  ]},

{ lead:['El camino de vuelta.', 'Primavera.', 'Año 1805.'],
  xml:'Kenzo en el camino entre Matsumoto y Kuromi. Mochila al hombro. Las montañas. Los campos.',
  set:'camino', light:'dia', season:'primavera', opts:{tree:'sakura'},
  cast:[{who:'kenzo', pose:'bag', at:'center'}],
  lines:[
    N('Volví a Kuromi en primavera.'),
    N('Dos años después.'),
    N('Con más habilidad, más paciencia, y el formón de cerezo.'),
    N('También con la cajita. También con la grulla.'),
    N('También con cosas que no sabía cómo estaban.'),
    N('Pero volvía.'),
    N('Porque Kuromi era mi aldea.'),
    N('Y algunas cosas no se resuelven desde lejos.'),
  ]},

{ xml:'Kenzo entra a Kuromi. La aldea igual: el mercado, el taller de su padre, el señor Mori con sus especias.',
  set:'vista', light:'dia', season:'primavera',
  cast:[{who:'kenzo', pose:'bag', at:'center'}],
  lines:[
    N('La aldea estaba igual.'),
    N('El señor Mori con sus especias.'),
    N('Probablemente mal conservadas todavía.'),
    N('Mi padre en el taller.'),
    N('El camino al río.'),
    N('Todo igual.'),
    N('Yo no.'),
  ]},

{ xml:'Kenzo va directo al río. Se sienta en el lugar de siempre. El agua corriendo. Solo.',
  set:'rio', light:'tarde', season:'primavera', opts:{sun:true, tree:'sakura'},
  cast:[{who:'kenzo', pose:'sit', at:'center'}],
  lines:[
    N('Lo primero que hice fue ir al río.'),
    N('Me senté donde siempre.'),
    N('El río igual. Mismo sonido. Misma orilla.'),
    N('Solo que ahora solo.'),
    N('Y el lugar se sentía diferente sin ella.'),
    N('Como siempre se había sentido diferente sin ella.'),
    N('Solo que ahora lo sabía de antemano.'),
  ]},

{ xml:'Días después. Kenzo en el mercado, una mañana cualquiera. Ve a Hiro — el hijo del herrero, del grupo de arquería. Camina tranquilo. Buen muchacho, se le nota.',
  set:'mercado', light:'dia', season:'primavera',
  cast:[{who:'hiro', pose:'stand', at:'center'}],
  lines:[
    N('Vi a Hiro antes de ver a Hana.'),
    N('El hijo del herrero.'),
    N('Siempre lo había visto por la aldea.'),
    N('Pero ahora lo vi diferente.'),
    N('Caminaba tranquilo. Saludaba bien.'),
    N('No era arrogante. No era ruidoso.'),
    N('Era simplemente alguien que sabía quién era.'),
    N('Y eso era suficiente.'),
    N('Eso siempre es suficiente.'),
  ]},

{ xml:'Hiro pasa cerca de Kenzo. Lo ve. Asiente como saludo — sin tensión, no sabe nada. Solo dos personas de la misma aldea cruzándose.',
  set:'mercado', light:'dia', season:'primavera',
  cast:[{who:'kenzo', pose:'stand', at:'left'}, {who:'hiro', pose:'stand', at:'right'}],
  lines:[
    N('Me saludó.'),
    N('Como saluda uno a alguien que conoce de vista.'),
    N('Sin historia. Sin peso.'),
    N('Solo: hola.'),
    N('Yo respondí igual.'),
    N('Y seguí mi camino.'),
    N('Pensando en que era difícil no caerle bien a alguien así.'),
    N('Y que eso no me ayudaba en nada.'),
  ]},

{ xml:'Kenzo esa tarde en el río. Solo. Sentado. El agua corriendo.',
  set:'rio', light:'atardecer', season:'primavera', opts:{tree:'sakura'},
  cast:[{who:'kenzo', pose:'sit', at:'center'}],
  lines:[
    N('Fui al río esa tarde. Solo.'),
    N('Me senté donde siempre.'),
    N('Y pensé en algo que no quería pensar.'),
    N('Que Hiro no era un obstáculo. Era una persona.'),
    N('Y que la vida de Hana había seguido.'),
    N('Como tenía todo el derecho de seguir.'),
    N('Y que yo había llegado tarde.'),
    N('No porque alguien me hubiera bloqueado el camino.'),
    N('Sino porque el camino siguió sin mí.'),
    N('Y eso no tiene solución.'),
    N('Solo tiene aceptación.'),
  ]},

{ lead:['Días después.', 'El mercado.', 'Una mañana.'],
  xml:'Kenzo en el mercado. Al fondo, frente al puesto de especias del señor Mori, Hana. De espaldas. El mismo kimono gris, más desgastado. El perro amarrado cerca, más viejo.',
  set:'mercado', light:'dia', season:'primavera',
  cast:[{who:'hana', pose:'back', at:'center'}], dog:{pos:'right', dx:-50},
  breakText:['Dos años.', 'El río siguió igual.', 'Ellos no.', 'Pero ahí estaban los dos.', 'En la misma esquina de siempre.', 'Como si el tiempo hubiera dado un círculo enorme.', 'Y hubiera terminado exactamente donde empezó.'],
  lines:[
    N('La vi unos días después.'),
    N('En el mercado. De espaldas.'),
    N('Rechazando especias. Como la primera vez.'),
    N('Dos años después.'),
    N('El perro más viejo pero ahí.'),
    N('Y yo parado en la misma esquina.'),
    N('Con los pies que no terminaban de moverse.'),
    N('Porque una parte de mí quería quedarse ahí un momento más.'),
    N('Antes de que todo cambiara de lugar.'),
    N('Antes de que fuera real de otra manera.'),
  ]},

];

window.STORY = STORY;
window.STORY_COMPLETE = false;   // capítulos 3–5 pendientes
