/* =========================================================================
   DISTANCIA — story.js
   Guión corregido · Capítulos 1–5 (edición de novela visual)

   page = {
     chapter?, chapterName?, intro?[]   // 1ª página del capítulo (PANTALLA DE CAPÍTULO)
     lead?[]                            // tarjeta de tiempo en negro antes de la escena
     bg, light, season, opts?           // composición visual
     chars?: [{ key, pos, sit, dim, width, dx, bottom }]
     dog?:  true | { pos, dx }
     prop?: 'crane' | 'box' | 'note'
     lines: [...]
     breakText?                         // interludio en negro tras la página
   }

   Tipos de línea:
     N(t)   narrador
     SP(t)  NARRADOR ESPECIAL  (ancla emocional / eco entre capítulos)
     E/A    diálogo de Él / Ella  (segundo arg = acotación)
     Bc(t)  silencio cómodo      Bl(t) silencio largo
     Bi(t)  silencio incómodo    Pv(t) pausa visual
   ========================================================================= */
const N  = (t) => ({ s:'narrador', t });
const SP = (t) => ({ s:'special',  t });
const E  = (t,note) => note ? ({s:'Él', t, note})   : ({s:'Él', t});
const A  = (t,note) => note ? ({s:'Ella', t, note}) : ({s:'Ella', t});
const Bc = (t='') => ({ s:'beat', k:'comodo',   t });
const Bl = (t='') => ({ s:'beat', k:'largo',    t });
const Bi = (t='') => ({ s:'beat', k:'incomodo', t });
const Pv = (t='') => ({ s:'beat', k:'pausa',    t });

const STORY = [

/* ============================ CAPÍTULO 1 ============================
   "El olor de las especias nuevas" */
{ chapter:'Capítulo 1', chapterName:'El olor de las especias nuevas',
  intro:['Primavera.', 'Él lleva toda su vida en esta aldea.', 'Ella acaba de llegar.'],
  bg:'mercado', light:'amanecer', season:'primavera', chars:[{key:'el', pos:'center', width:'48%'}],
  lines:[
    SP('Yo era el tipo de persona que llenaba los cuartos.'),
    Bc(),
    N('No porque fuera el más importante.'),
    N('Sino porque no sabía estar en silencio cuando había espacio para algo más.'),
    Pv('un pétalo cruza la pantalla'),
    N('Eso a veces era un don.'),
    N('A veces no.'),
  ]},

{ bg:'mercado', light:'amanecer', season:'primavera', chars:[{key:'ellaBack', pos:'center', width:'52%'}],
  lines:[
    N('La primera vez que te vi, estabas rechazando especias.'),
    Bc(),
    N('Una por una.'),
    N('Con la cara de alguien que tiene estándares y no planea bajarlos.'),
  ]},

{ bg:'mercado', light:'dia', season:'primavera', chars:[{key:'ella', pos:'center', width:'50%'}],
  lines:[
    N('Sacaste una lista.'),
    N('La doblaste en exactamente los mismos dobleces de antes.'),
    Bc(),
    N('Y seguiste tu camino como si el mercado entero fuera un trámite.'),
    Pv(),
    N('Me quedé parado.'),
    N('Con los sacos en la mano.'),
    N('Sin saber bien por qué.'),
  ]},

{ bg:'mercado', light:'dia', season:'primavera', chars:[{key:'el', pos:'center', width:'48%'}],
  lines:[
    N('Volteé tres veces.'),
    N('Ya no estabas.'),
    Bc(),
    N('El señor del puesto me vio volteando.'),
    N('Fingí que estaba contando los sacos.'),
    Bc(),
    N('No estaba contando los sacos.'),
  ]},

{ lead:['Días después.'],
  bg:'rio', light:'tarde', season:'primavera', opts:{sun:true, tree:'sakura'},
  chars:[{key:'el', pos:'left', width:'48%'}, {key:'ellaHold', pos:'right', width:'48%'}],
  dog:{pos:'right', dx:-92},
  lines:[
    N('Te empecé a ver por la aldea.'),
    Bc(),
    N('Y una tarde cambié mi ruta para que coincidiera con la tuya.'),
    Pv('el río suena a lo lejos'),
    N('A mitad del camino me arrepentí.'),
    N('Ya era tarde.'),
  ]},

{ bg:'rio', light:'tarde', season:'primavera', opts:{tree:'sakura'},
  chars:[{key:'el', pos:'left', width:'48%'}, {key:'ella', pos:'right', width:'48%'}],
  dog:{pos:'center', dx:0},
  lines:[
    E('Buenas tardes.'),
    A('Buenas tardes.', '(un segundo antes de responder)'),
    E('¿Eres nueva en la aldea? No te había visto antes.'),
    Bi(),
    N('Mentira.'),
    N('Te había visto tres veces.'),
    N('Pero no podía decir eso.'),
  ]},

{ bg:'rio', light:'tarde', season:'primavera', opts:{tree:'sakura'},
  chars:[{key:'el', pos:'left', width:'48%'}, {key:'ella', pos:'right', width:'48%'}],
  dog:{pos:'center', dx:0},
  lines:[
    A('Llegué hace un mes con mi familia.'),
    E('¿Y cómo te ha parecido la aldea?'),
    A('Las hierbas del mercado no están bien conservadas. Pierden propiedades.', '(lo piensa de verdad)'),
    Pv(),
    E('...Ah.'),
    Bc(),
    N('Eso no era lo que esperaba.'),
    N('Esperaba algo sobre el clima.'),
    N('O sobre la gente.'),
    N('Las hierbas no.'),
  ]},

{ bg:'rio', light:'tarde', season:'primavera', opts:{tree:'sakura'},
  chars:[{key:'el', pos:'left', width:'48%'}, {key:'ella', pos:'right', width:'48%'}],
  lines:[
    A('¿Qué?'),
    E('Nada. Es que pregunté cómo te había parecido la aldea.'),
    A('Y eso es lo que me ha parecido.'),
    E('Las hierbas.'),
    A('Las hierbas importan.'),
    Bc(),
    N('No había ironía.'),
    N('Solo una persona que tenía criterio propio y no veía razón para esconderlo.'),
    Bc(),
    N('No supe qué hacer con eso.'),
    N('Pero me gustó.'),
  ]},

{ bg:'rio', light:'atardecer', season:'primavera', opts:{tree:'sakura'},
  chars:[{key:'el', pos:'left', width:'48%'}, {key:'ellaBack', pos:'right', width:'48%'}],
  dog:{pos:'right', dx:-40},
  lines:[
    N('Se fue.'),
    N('El perro también.'),
    Bc(),
    N('Obediente cuando ella lo llamaba.'),
    N('Lo cual decía algo de ella.'),
    Pv(),
    N('No supe qué exactamente.'),
    N('Pero algo.'),
  ]},

{ bg:'rio', light:'atardecer', season:'primavera', opts:{sun:true, tree:'sakura'},
  chars:[{key:'elSit', pos:'center', sit:true, width:'50%'}],
  lines:[
    N('Llegué al río.'),
    N('Me senté.'),
    Bl(),
    N('Y me di cuenta que no recordaba para qué había venido al río.'),
    Bc(),
    N('Solo recordaba: las hierbas del mercado no están bien conservadas.'),
    N('Dicho con esa cara.'),
    N('Con esa seriedad absurda.'),
    Pv('el río'),
    N('Me reí solo.'),
    N('El río me ignoró.'),
  ]},

{ bg:'casanoche', light:'noche', season:'primavera', chars:[{key:'el', pos:'center', width:'46%'}],
  lines:[
    SP('Esa noche pensé en ti por primera vez.'),
    Bc(),
    N('Me pregunté cómo te llamabas.'),
    N('Me pregunté qué hacías con todas esas hierbas.'),
    N('Me pregunté si el perro dormía adentro o afuera.'),
    N('Me pregunté si todas tus listas estaban escritas con ese mismo cuidado.'),
    Pv('una estrella, el silencio'),
    N('Cosas sin importancia.'),
    N('Muchas cosas sin importancia.'),
    Bc(),
    N('Eso ya era algo.'),
  ]},

/* ============================ CAPÍTULO 2 ============================
   "Lo que no se dice en voz alta" */
{ chapter:'Capítulo 2', chapterName:'Lo que no se dice en voz alta',
  intro:['Las semanas siguientes.', 'Él busca pretextos.', 'Ella no los necesita.'],
  bg:'rio', light:'dia', season:'primavera', opts:{tree:'sakura', ducks:true},
  chars:[{key:'el', pos:'left', width:'48%'}, {key:'ellaSit', pos:'right', sit:true, width:'50%'}],
  dog:{pos:'center', dx:10},
  lines:[
    N('Empecé a ir al río más temprano.'),
    Bc(),
    N('Por el agua, obviamente.'),
    Bc(),
    N('El agua es importante.'),
    N('Muy importante.'),
    N('El cubo lo confirmaba.'),
  ]},

{ bg:'rio', light:'dia', season:'verano', opts:{tree:'sakura', ducks:true},
  chars:[{key:'elSit', pos:'left', sit:true, width:'50%'}, {key:'ellaSit', pos:'right', sit:true, width:'50%'}],
  dog:{pos:'center', dx:0},
  lines:[
    E('¿Esta no sirve?'),
    A('Está cortada mal.'),
    E('¿Cómo se corta mal una hierba?'),
    A('De muchas maneras.', '(lo mira como si la pregunta fuera muy larga de responder)'),
    Bl(),
    N('La dejé en el suelo.'),
    N('No volví a recoger hierbas.'),
  ]},

{ bg:'templo', light:'tarde', season:'primavera', opts:{night:false},
  chars:[{key:'elSit', pos:'left', sit:true, width:'50%'}, {key:'ellaSit', pos:'right', sit:true, width:'50%'}],
  prop:'note',
  lines:[
    Pv('hojas de primavera filtrando la luz'),
    E('¿Qué son?'),
    A('Cosas.'),
    E('¿Para quién?'),
    A('Para quien los necesite.'),
    E('¿Me enseñas a hacer uno?'),
    A('No tienes paciencia para esto.', '(lo mira — evalúa)'),
    E('Claro que sí.'),
    A('Llevas aquí dos minutos y ya preguntaste cuatro cosas.'),
    Bi(),
    N('No tenía respuesta para eso.'),
    N('Porque tenía razón.'),
  ]},

{ bg:'templo', light:'tarde', season:'primavera', opts:{night:false},
  chars:[{key:'elSit', pos:'left', sit:true, width:'50%'}, {key:'ellaSit', pos:'right', sit:true, width:'50%'}],
  lines:[
    Bl(),
    N('Me quedé callado dos minutos.'),
    N('Para mí eso era mucho.'),
    Bc(),
    N('Casi dije algo cuatro veces.'),
    N('Me las aguanté las cuatro.'),
    Pv(),
    N('No me dijo nada.'),
    N('Pero tampoco me pidió que me fuera.'),
    N('Conté eso como victoria.'),
  ]},

{ bg:'templo', light:'tarde', season:'primavera', opts:{night:false},
  chars:[{key:'elSit', pos:'left', sit:true, width:'50%'}, {key:'ellaSit', pos:'right', sit:true, width:'50%'}],
  prop:'note',
  lines:[
    Bc(),
    N('Deshiciste una que ya estaba terminada.'),
    N('Y empezaste de nuevo.'),
    Bc(),
    N('No pregunté por qué.'),
    SP('Aprendí que con ciertas cosas tú eras el estándar.'),
    N('Y el estándar no se negocia.'),
  ]},

{ lead:['Festival menor de la aldea.', 'Esa noche.'],
  bg:'puente', light:'noche', season:'verano',
  chars:[{key:'elSit', pos:'left', sit:true, width:'50%'}, {key:'ellaSit', pos:'right', sit:true, width:'50%'}],
  dog:{pos:'right', dx:-10},
  lines:[
    E('¿No entras?'),
    A('Estoy bien aquí.'),
    E('Hay comida adentro.'),
    A('He visto lo que venden. No.'),
    E('¿Qué tiene de malo?', '(ríe)'),
    A('Demasiado dulce. Sin criterio.'),
    Bc(),
    N('Me senté en el puente.'),
    N('Sin que me lo ofrecieran.'),
    N('Como siempre.'),
  ]},

{ bg:'puente', light:'noche', season:'verano',
  chars:[{key:'elSit', pos:'left', sit:true, width:'50%'}, {key:'ellaSit', pos:'right', sit:true, width:'50%'}],
  dog:{pos:'center', dx:0},
  lines:[
    E('Entonces... ¿qué sí te gusta comer?'),
    A('Pocas cosas.', '(piensa genuinamente)'),
    E('¿Cuántas es pocas?'),
    A('Las suficientes.'),
    E('Eso no es una respuesta.'),
    A('Es la única que tengo.'),
    Bc(),
    N('Me devolviste mis propias palabras del río.'),
    Bc(),
    N('No sé si fue intencional.'),
    N('Probablemente sí.'),
    N('Probablemente no lo ibas a admitir.'),
  ]},

{ bg:'puente', light:'noche', season:'verano',
  chars:[{key:'elSit', pos:'left', sit:true, width:'50%'}, {key:'ellaSit', pos:'right', sit:true, width:'50%'}],
  prop:'note',
  lines:[
    Pv('luz dorada de linternas sobre el papel'),
    N('Empezaste a doblar algo.'),
    N('Sin decir qué.'),
    Bc(),
    N('Me quedé callado.'),
    N('Esta vez no costó tanto.'),
  ]},

{ lead:['Días después.', 'El río.'],
  bg:'rio', light:'tarde', season:'verano', opts:{sun:true, tree:'sakura'},
  chars:[{key:'elSit', pos:'left', sit:true, width:'50%'}, {key:'ella', pos:'right', width:'48%'}],
  lines:[
    E('Está muy bueno.'),
    A('Lo sé.'),
    E('¿Nunca puedo solo decirte que algo está bueno?', '(ríe)'),
    A('Puedes. Pero es vago.'),
    E('Está... equilibrado. No pelea consigo mismo.'),
    A('Eso sí.', '(un momento)'),
    Bc(),
    N('Encontré la manera.'),
    N('Ser específico.'),
    SP('Siempre ser específico.'),
  ]},

{ bg:'rio', light:'tarde', season:'verano', opts:{tree:'sakura'},
  chars:[{key:'elSit', pos:'left', sit:true, width:'50%'}, {key:'ellaSit', pos:'right', sit:true, width:'50%'}],
  lines:[
    N('Contaba cosas.'),
    N('Cosas del día. Cosas que vi. Cosas que me parecían graciosas.'),
    Pv('el agua, el silencio entre frases'),
    N('Tú no reías en el momento.'),
    N('A veces reías treinta segundos después.'),
    N('Como si el chiste necesitara tiempo de procesar.'),
    Bc(),
    N('Aprendí a esperar los treinta segundos.'),
  ]},

{ lead:['Una mañana.', 'Él llega a buscarla.', 'Ella no está.'],
  bg:'casanoche', light:'amanecer', season:'verano', chars:[{key:'el', pos:'center', width:'46%'}], prop:'note',
  lines:[
    Bl(),
    N('Dejaste algo en tu propia puerta.'),
    N('Para mí.'),
    N('Un papel doblado.'),
    Bc(),
    N('No era una nota larga.'),
    N('Decía que las hierbas del río del norte eran mejores.'),
    N('Y que si quería acompañarla mañana, podía.'),
    Pv(),
    SP('Una invitación de cuatro palabras disfrazada de información botánica.'),
    N('Aprendí a leer entre tus líneas desde ese día.'),
  ]},

{ lead:['El río del norte.', 'Más lejos. Más tranquilo.'],
  bg:'rio', light:'dia', season:'verano', opts:{tree:'sakura', ducks:true},
  chars:[{key:'el', pos:'left', width:'48%'}, {key:'ellaHold', pos:'right', width:'48%'}],
  dog:{pos:'center', dx:0},
  lines:[
    N('No me explicaste por qué la primera no servía.'),
    N('Solo la regresaste.'),
    Bc(),
    N('Aprendí más de lo que rechazabas que de lo que aceptabas.'),
    Pv('hojas, el viento entre las ramas'),
    N('De las hierbas y de todo lo demás.'),
  ]},

{ bg:'rio', light:'tarde', season:'verano', opts:{tree:'sakura'},
  chars:[{key:'elSit', pos:'left', sit:true, width:'50%'}, {key:'ellaSit', pos:'right', sit:true, width:'50%'}],
  dog:{pos:'center', dx:0},
  lines:[
    Bl(),
    E('¿Puedo preguntar algo?'),
    A('Depende.'),
    E('¿Por qué doblas el papel siempre igual?'),
    A('Porque si lo doblas diferente cada vez, al final no sabes dónde está lo importante.', '(pausa)'),
    Bc(),
    N('Estabas hablando del papel.'),
    N('Creo.'),
  ]},

{ bg:'rio', light:'tarde', season:'verano', opts:{tree:'sakura'},
  chars:[{key:'elSit', pos:'left', sit:true, width:'50%'}, {key:'ellaSit', pos:'right', sit:true, width:'50%'}],
  prop:'note',
  lines:[
    E('¿Cómo lo haces igual cada vez?'),
    A('Práctica.'),
    E('¿Cuánta práctica?'),
    A('Más de la que tienes.', '(lo mira, luego a su papel torcido)'),
    Bc(),
    N('No era cruel.'),
    N('Era honesta.'),
    Pv(),
    N('Que a veces se sentía igual pero no lo era.'),
  ]},

{ bg:'rio', light:'atardecer', season:'verano', opts:{tree:'sakura'},
  chars:[{key:'elSit', pos:'left', sit:true, width:'50%'}, {key:'ellaSit', pos:'right', sit:true, width:'50%'}],
  dog:{pos:'center', dx:0}, prop:'crane',
  lines:[
    Pv('el río, la grulla entre los dos'),
    N('La dejaste ahí.'),
    N('Sin decir nada.'),
    N('Sin mirarme cuando la tomé.'),
    N('Como si no hubiera pasado nada importante.'),
    Bc(),
    SP('La guardé esa noche en una caja de madera.'),
    N('En el lugar de más arriba.'),
    N('Donde la encontraría primero.'),
  ]},

{ lead:['Las semanas siguientes.'],
  bg:'rio', light:'tarde', season:'verano', opts:{tree:'sakura'},
  chars:[{key:'elSit', pos:'left', sit:true, width:'50%'}, {key:'ellaSit', pos:'right', sit:true, width:'50%'}],
  dog:{pos:'center', dx:0},
  lines:[
    Pv('hojas, luz entre tardes distintas'),
    N('Hubo una costumbre que se formó sin que ninguno la decidiera.'),
    N('El río. Las hierbas. El papel.'),
    Bc(),
    N('Yo hablando.'),
    N('Tú escuchando.'),
    N('Yo metiendo la pata.'),
    N('Tú mirándome con esa cara.'),
    N('Yo intentando arreglarlo.'),
    N('Tú sin ayudarme.'),
    Bc(),
    N('Era un sistema.'),
  ]},

{ bg:'rio', light:'tarde', season:'verano', opts:{tree:'sakura'},
  chars:[{key:'elSit', pos:'left', sit:true, width:'50%'}, {key:'ellaSit', pos:'right', sit:true, width:'50%'}],
  lines:[
    N('Ese día te pregunté qué estudiabas.'),
    N('Me explicaste durante mucho tiempo.'),
    N('Sin verificar si yo seguía el hilo.'),
    N('Completo.'),
    Pv('el agua, la voz de ella, la tarde'),
    E('No entendí casi nada.', '(cuando ella termina)'),
    A('¿Por qué no me detuviste?', '(pausa)'),
    E('Porque me gustaba escucharte.'),
    Bl(),
    N('Te callaste.'),
    N('Miraste el río.'),
    Bc(),
    N('Pero tus orejas se pusieron un poco rojas.'),
    N('Lo vi.'),
    N('No dije nada.'),
    SP('Guardé eso también.'),
  ]},

{ bg:'cuarto', light:'noche', season:'verano', chars:[], prop:'box',
  lines:[
    SP('Guardaba todo lo que me dabas.'),
    N('Las notas dobladas.'),
    N('Las figuras de papel.'),
    N('Los silencios que dejabas caer como si no pesaran.'),
    Pv('la llama de la vela'),
    N('Entendí que cada cosa que dabas te costaba algo.'),
    N('Tiempo. Atención.'),
    N('El esfuerzo de decir sin decir.'),
    Bc(),
    N('Tú no dabas cosas a la ligera.'),
    N('Y eso significaba que yo tampoco era a la ligera.'),
    Bl(),
    N('O eso quería creer.'),
  ]},

/* ============================ CAPÍTULO 3 ============================
   "Lo que se enfrió sin avisar" */
{ chapter:'Capítulo 3', chapterName:'Lo que se enfrió sin avisar',
  intro:['Verano.', 'Él lleva meses guardando algo.', 'Hoy lo va a decir.'],
  bg:'rio', light:'tarde', season:'verano', opts:{sun:true, tree:'sakura'},
  chars:[{key:'elSit', pos:'left', sit:true, width:'50%'}, {key:'ellaSit', pos:'right', sit:true, width:'50%'}],
  dog:{pos:'center', dx:0},
  lines:[
    SP('Hubo una tarde que decidí decirlo.'),
    Bc(),
    N('No porque tuviera un plan.'),
    N('Sino porque guardarlo ya pesaba más que el miedo a decirlo.'),
  ]},

{ bg:'rio', light:'tarde', season:'verano', opts:{tree:'sakura'},
  chars:[{key:'elSit', pos:'left', sit:true, width:'50%'}, {key:'ellaSit', pos:'right', sit:true, width:'50%'}],
  dog:{pos:'center', dx:0},
  lines:[
    Bl(),
    E('Tengo que decirte algo.'),
    A('Dilo.', '(quieta)'),
    Bc(),
    E('Me gustas.'),
    E('Desde hace tiempo.'),
    E('Y no lo había dicho porque no sabía cómo, pero ya sé que si no lo digo me voy a arrepentir.'),
    Pv('el río · el perro que no se mueve'),
    SP('Dijiste: ah.'),
    Bc(),
    N('Solo eso.'),
    N('Ah.'),
  ]},

{ bg:'rio', light:'atardecer', season:'verano', opts:{tree:'sakura'},
  chars:[{key:'elSit', pos:'left', sit:true, width:'50%'}, {key:'ellaSit', pos:'right', sit:true, width:'50%'}],
  lines:[
    Bl(),
    N('No dijiste nada más por un rato.'),
    N('Y yo aprendí a esperar tus treinta segundos.'),
    Pv(),
    N('Así que esperé.'),
    Bc(),
    N('Esta vez fueron más de treinta segundos.'),
  ]},

{ bg:'rio', light:'atardecer', season:'verano', opts:{tree:'sakura'},
  chars:[{key:'elSit', pos:'left', sit:true, width:'50%'}, {key:'ellaSit', pos:'right', sit:true, width:'50%'}],
  lines:[
    A('No sé qué decirte.'),
    E('No tienes que decir nada ahorita.'),
    A('¿Estás seguro de lo que dices?', '(pausa)'),
    E('Sí.'),
    A('Okay.'),
    Bc(),
    N('Okay.'),
    N('No era un sí.'),
    N('No era un no.'),
    Bc(),
    N('Era ella siendo honesta sobre no saber.'),
    SP('Y yo lo respeté.'),
    N('Aunque no supiera bien qué hacer con eso.'),
  ]},

{ lead:['Las semanas siguientes.', 'Las cosas siguieron igual.', 'Y también no.'],
  bg:'rio', light:'dia', season:'verano', opts:{tree:'sakura', ducks:true},
  chars:[{key:'elSit', pos:'left', sit:true, width:'50%'}, {key:'ellaSit', pos:'right', sit:true, width:'50%'}],
  lines:[
    N('Las cosas siguieron.'),
    N('El río. Las hierbas. El papel.'),
    Bc(),
    N('Pero algo había cambiado de lugar.'),
    N('No de manera dramática.'),
    Bc(),
    N('Solo que ahora lo que había entre nosotros tenía nombre.'),
    N('Y ninguno de los dos sabía bien qué hacer con el nombre.'),
  ]},

{ bg:'rio', light:'dia', season:'verano', opts:{tree:'sakura'},
  chars:[{key:'elSit', pos:'left', sit:true, width:'50%'}, {key:'ellaSit', pos:'right', sit:true, width:'50%'}],
  lines:[
    E('¿Estás bien?'),
    A('Sí.'),
    E('¿Segura?'),
    A('Sí.'),
    E('¿Estás segura de que estás segura?'),
    Bi('— ella solo lo mira —'),
    E('Eso fue demasiado.'),
    A('Sí.'),
    Bc(),
    N('Al menos en eso fuimos honestos los dos.'),
  ]},

{ lead:['Semanas después.', 'La situación fue enfriándose sola.', 'Sin drama. Solo fue.'],
  bg:'rio', light:'nublado', season:'verano', opts:{tree:'sakura'},
  chars:[{key:'elSit', pos:'left', sit:true, width:'50%'}, {key:'ella', pos:'right', width:'46%'}],
  lines:[
    Bl(),
    N('No hubo un momento exacto.'),
    N('Esas cosas no tienen momento exacto.'),
    Pv('el agua siguiendo'),
    N('Solo un día el aire era diferente.'),
    N('Y los dos lo sabíamos.'),
    Bc(),
    N('Y ninguno lo decía.'),
  ]},

{ bg:'templo', light:'dia', season:'verano', opts:{night:false},
  chars:[{key:'el', pos:'left', dim:true, width:'42%'}, {key:'ella', pos:'center', width:'42%', dx:-26}, {key:'hiro', pos:'right', width:'46%'}],
  lines:[
    Pv('distancia, luz de mediodía'),
    SP('Tenías un mundo antes de mí.'),
    N('Yo lo sabía.'),
    N('Pero ese día lo vi.'),
    Bc(),
    N('Y entendí que ese mundo tenía sus propias personas.'),
    N('Sus propios vínculos.'),
    N('Formados con años.'),
    Bl(),
    N('Yo no tenía años.'),
    N('Solo tenía un verano.'),
  ]},

{ bg:'rio', light:'nublado', season:'verano', opts:{tree:'sakura'},
  chars:[{key:'elSit', pos:'left', sit:true, width:'50%'}, {key:'ellaSit', pos:'right', sit:true, width:'50%'}],
  lines:[
    Bl(),
    N('Llegaste al río con algo tomado.'),
    N('Lo noté en cómo te sentaste.'),
    Bc(),
    N('Derecha.'),
    N('Como cuando tienes algo que decir y sabes que lo vas a decir.'),
  ]},

{ bg:'rio', light:'nublado', season:'verano', opts:{tree:'sakura'},
  chars:[{key:'elSit', pos:'left', sit:true, width:'50%'}, {key:'ellaSit', pos:'right', sit:true, width:'50%'}],
  prop:'note',
  lines:[
    A('Léelo después.'),
    E('¿Por qué después?'),
    A('Porque si lo lees ahora tengo que seguir aquí.', '(pausa)'),
    Bi(),
    SP('Eso me lo dijo todo.'),
    N('No necesité leer el papel todavía.'),
  ]},

{ bg:'rio', light:'tarde', season:'verano', opts:{tree:'sakura'},
  chars:[{key:'elSit', pos:'center', sit:true, width:'50%'}], prop:'note',
  lines:[
    Pv('el río, el sonido del agua, él solo'),
    Bl(),
    N('Lo leí tres veces.'),
    N('No porque no lo entendiera.'),
    N('Sino porque quería estar seguro de que decía lo que decía.'),
    Bc(),
    N('Decía que había alguien más.'),
    N('Alguien de su mundo de antes.'),
    N('Que lo sentía.'),
    Pv(),
    N('Tres líneas.'),
    N('Precisas.'),
    N('Como todo lo suyo.'),
  ]},

{ bg:'templo', light:'atardecer', season:'verano',
  chars:[{key:'elSit', pos:'center', sit:true, width:'50%'}],
  lines:[
    N('No estaba enojado.'),
    N('No podía.'),
    Bc(),
    N('Me dijo la verdad.'),
    N('Con un papel porque de frente no podía.'),
    N('Pero me la dijo.'),
    Bc(),
    N('Y la persona que eligió no era mala.'),
    N('Eso era lo más difícil.'),
    Pv(),
    N('Era alguien que la conocía de antes.'),
    N('Con años.'),
    SP('Yo no podía competir con años.'),
    N('Tampoco era justo intentarlo.'),
  ]},

{ bg:'rio', light:'tarde', season:'verano', opts:{tree:'sakura'},
  chars:[{key:'elSit', pos:'center', sit:true, width:'50%'}],
  lines:[
    Pv('el río, siempre el río'),
    N('Me senté en el río.'),
    N('Nuestro río, aunque ya no.'),
    Bl(),
    N('Y no me sentí con derecho a estar enojado.'),
    Bc(),
    N('Le dije lo que sentía.'),
    N('Ella fue honesta sobre lo que sentía.'),
    N('Así funcionan las cosas cuando las dos personas son decentes.'),
    Pv(),
    SP('Duele igual.'),
    N('Pero duele limpio.'),
  ]},

{ lead:['Tiempo después.', 'Él la apoyó desde lejos.', 'Sin que ella se lo pidiera.'],
  bg:'aldea', light:'dia', season:'verano', opts:{tree:'sakura'},
  chars:[{key:'el', pos:'left', width:'44%'}, {key:'ella', pos:'right', dim:true, width:'40%', dx:-44}, {key:'hiro', pos:'right', dim:true, width:'42%'}],
  lines:[
    N('Te vi con él.'),
    N('Y seguí mi camino.'),
    Bc(),
    N('No porque no doliera.'),
    N('Sino porque no tenía derecho a que doliera en voz alta.'),
    Bl(),
    N('Ya había dicho lo mío.'),
    N('Tú habías dicho lo tuyo.'),
    N('El resto era tuyo.'),
  ]},

{ bg:'cuarto', light:'noche', season:'verano', chars:[], prop:'box',
  lines:[
    Pv('la caja cerrada'),
    N('Guardé el último papel con los demás.'),
    N('El que tenía más dobleces.'),
    Bc(),
    N('No lo tiré.'),
    N('No sé si eso fue sabiduría o terquedad.'),
    Bc(),
    N('Probablemente las dos.'),
    SP('Pasaron años.'),
    N('Muchos.'),
  ]},

/* ============================ CAPÍTULO 4 ============================
   "Lo que cambia cuando nadie mira" */
{ chapter:'Capítulo 4', chapterName:'Lo que cambia cuando nadie mira',
  intro:['Los años siguientes.', 'Él en la aldea.', 'Cada uno en su camino.'],
  bg:'mercado', light:'otono', season:'otono', chars:[{key:'el', pos:'center', width:'46%'}],
  lines:[
    N('El primer otoño fue el más difícil.'),
    Bc(),
    N('No porque hiciera algo dramático.'),
    Pv('una hoja cruzando la pantalla'),
    N('Sino porque todo seguía igual y tú ya no estabas en los mismos lugares.'),
    N('O sí estabas.'),
    Bl(),
    N('Solo que ya no era para mí.'),
  ]},

{ bg:'rio', light:'otono', season:'otono', opts:{tree:'otono', hill:'#8a7a4a', bank:'#9a8a52', frontBank:'#a8985a', frontBank2:'#b4a466'},
  chars:[{key:'elSit', pos:'center', sit:true, width:'50%'}],
  lines:[
    Pv('el río solo, el sonido del agua'),
    N('Seguí yendo al río.'),
    N('No sé exactamente por qué.'),
    Bc(),
    N('Supongo que los lugares guardan algo de las personas que estuvieron en ellos.'),
    Bc(),
    N('Y yo todavía quería estar cerca de algo tuyo.'),
    N('Aunque fuera el agua.'),
  ]},

{ lead:['Invierno.'],
  bg:'cuarto', light:'noche', season:'invierno', chars:[], prop:'box',
  lines:[
    N('Una noche de invierno saqué todo.'),
    N('No para tirarlo.'),
    Bc(),
    N('Solo para recordar que había pasado.'),
    N('Que no me lo había inventado.'),
    Pv('la grulla en la mano'),
    N('Que hubo un río y un perro y papeles doblados con demasiado cuidado.'),
    SP('Y que estuvo bien mientras estuvo.'),
  ]},

{ lead:['Primavera.', 'La vida sigue.'],
  bg:'mercado', light:'dia', season:'primavera', chars:[{key:'el', pos:'center', width:'48%'}],
  lines:[
    Pv('pétalos, el mercado, la aldea viva'),
    N('Cambié en esos años.'),
    N('No de golpe.'),
    Bc(),
    N('Aprendí a escuchar más.'),
    N('Aprendí que no todo silencio necesita llenarse.'),
    Bc(),
    N('Lo aprendí cuando lo aprendí.'),
    N('Tarde.'),
    SP('Pero lo aprendí.'),
  ]},

{ lead:['Verano.', 'Un año después.'],
  bg:'mercado', light:'dia', season:'verano', chars:[{key:'el', pos:'center', width:'48%'}],
  lines:[
    N('Compré una especia.'),
    N('No supe si era buena.'),
    Bc(),
    N('Nunca aprendí a distinguirlas bien.'),
    Pv(),
    N('Pero me pregunté qué habrías dicho tú.'),
    Bc(),
    N('Probablemente que estaba mal conservada.'),
    N('Probablemente tenías razón.'),
  ]},

{ lead:['Segundo otoño.'],
  bg:'rio', light:'otono', season:'otono', opts:{tree:'otono', hill:'#8a7a4a', bank:'#9a8a52', frontBank:'#a8985a', frontBank2:'#b4a466'},
  chars:[{key:'elSit', pos:'center', sit:true, width:'50%'}],
  lines:[
    Pv('una hoja sobre el agua'),
    N('El segundo otoño fue diferente.'),
    N('No porque te hubiera olvidado.'),
    Bc(),
    SP('Sino porque aprendí a cargar el recuerdo sin que me aplastara.'),
    Pv(),
    N('Eso también se aprende.'),
    N('Aunque nadie te avise que lo vas a necesitar.'),
  ]},

{ lead:['Los años pasan.', 'Él no la olvida.', 'Pero aprende a vivir con eso.'],
  bg:'casanoche', light:'noche', season:'invierno', chars:[{key:'el', pos:'center', width:'46%'}],
  lines:[
    N('Me pregunté más de una vez si pensarías en mí.'),
    N('No para hacerme daño.'),
    Bc(),
    N('Solo curiosidad genuina.'),
    Pv('el cielo, el silencio'),
    N('Si a veces ibas al río y el lugar te decía algo.'),
    N('Si el perro seguía siendo el mismo.'),
    N('Si seguías rechazando las especias mal conservadas.'),
    Bc(),
    N('Probablemente sí.'),
    N('Algunas cosas no cambian.'),
  ]},

{ lead:['Años después.', 'La aldea en primavera.'],
  bg:'rio', light:'dia', season:'primavera', opts:{tree:'sakura', ducks:true}, chars:[{key:'elBack', pos:'center', width:'48%'}],
  lines:[
    Pv('pétalos, el río, el camino'),
    N('Pasaron suficientes años como para que el río volviera a ser solo un río.'),
    Bc(),
    N('La mayoría de los días.'),
    N('No todos.'),
    Bc(),
    N('Pero la mayoría.'),
    SP('Eso también cuenta como avanzar.'),
  ]},

{ bg:'cuarto', light:'noche', season:'otono', chars:[], prop:'crane',
  lines:[
    Pv('la caja, la grulla, la vela'),
    N('Un día abrí la caja y no dolió.'),
    Bc(),
    N('Solo fue verdad.'),
    N('Que había pasado.'),
    N('Que había sido real.'),
    Bc(),
    N('Que te guardaba bien.'),
    SP('Sin saber que pronto iba a necesitar más espacio en esa caja.'),
  ]},

{ bg:'mercado', light:'otono', season:'otono',
  chars:[{key:'el', pos:'left', width:'46%'}, {key:'ellaBack', pos:'right', dim:true, width:'46%'}],
  breakText:'Como siempre.',
  lines:[
    N('No la busqué.'),
    N('Solo doblé una esquina.'),
  ]},

/* ============================ CAPÍTULO 5 ============================
   "Antes de que fuera bueno" */
{ chapter:'Capítulo 5', chapterName:'Antes de que fuera bueno',
  intro:['Otoño.', 'Años después.', 'Ella regresó a la aldea. Sola.'],
  bg:'mercado', light:'otono', season:'otono', chars:[{key:'ellaBack', pos:'center', width:'52%'}],
  dog:{pos:'right', dx:-50},
  lines:[
    N('Ahí estabas.'),
    N('Rechazando especias.'),
    N('Como la primera vez.'),
    Bc(),
    SP('El perro me reconoció antes que tú.'),
    N('Algunas cosas no cambian.'),
  ]},

{ bg:'mercado', light:'otono', season:'otono',
  chars:[{key:'el', pos:'left', width:'46%'}, {key:'ella', pos:'right', width:'46%'}],
  dog:{pos:'center', dx:0},
  lines:[
    Bl(),
    N('Nos quedamos quietos.'),
    N('El mercado siguió.'),
    Pv('el perro entre ellos, mirándolos'),
    N('El perro nos miró a los dos.'),
    N('Como preguntando por qué nadie se movía.'),
  ]},

{ bg:'mercado', light:'otono', season:'otono',
  chars:[{key:'el', pos:'left', width:'46%'}, {key:'ella', pos:'right', width:'46%'}],
  dog:{pos:'center', dx:0},
  lines:[
    Bl(),
    A('Hola.'),
    E('Hola.'),
    Bc(),
    A('Han pasado años.'),
    E('Sí.'),
    A('Te reconoció.', '(mira al perro, luego a él)'),
    E('Yo también te reconocí.'),
    Bc(),
    N('Algo se movió en tu cara.'),
    N('Muy poco.'),
    Pv(),
    N('Pero lo vi.'),
    SP('Siempre te vi.'),
  ]},

{ bg:'templo', light:'tarde', season:'otono', opts:{night:false},
  chars:[{key:'elSit', pos:'left', sit:true, width:'50%'}, {key:'ellaSit', pos:'right', sit:true, width:'50%'}],
  dog:{pos:'center', dx:0},
  lines:[
    E('¿Cómo has estado?'),
    A('Más o menos.', '(pausa real, más larga de lo normal)'),
    E('¿Más o menos qué?'),
    A('Más menos que más.', '(mira sus manos)'),
    Bl(),
    N('No pregunté más.'),
    N('Esperé.'),
    Bc(),
    N('Aprendí eso.'),
  ]},

{ bg:'templo', light:'noche', season:'otono',
  chars:[{key:'elSit', pos:'left', sit:true, width:'50%'}, {key:'ellaSit', pos:'right', sit:true, width:'50%'}],
  prop:'note',
  lines:[
    Pv('las linternas encendiéndose una por una'),
    N('Sacaste el papel.'),
    N('Pero no doblaste nada.'),
    N('Solo lo sostenías.'),
    Bl(),
    SP('Eso era nuevo.'),
    N('Nunca te había visto sostener el papel sin usarlo.'),
  ]},

{ bg:'templo', light:'noche', season:'otono',
  chars:[{key:'elSit', pos:'left', sit:true, width:'50%'}, {key:'ellaSit', pos:'right', sit:true, width:'50%'}],
  lines:[
    A('La persona con la que estuve... no era quien yo pensaba.'),
    Bl(),
    A('Me lastimó.'),
    Bl(),
    A('Mucho tiempo.'),
    Bl(),
    N('No dije nada.'),
    SP('Porque no había nada que decir que valiera más que escuchar.'),
  ]},

{ bg:'templo', light:'noche', season:'otono',
  chars:[{key:'elSit', pos:'left', sit:true, width:'50%'}, {key:'ellaSit', pos:'right', sit:true, width:'50%'}],
  dog:{pos:'center', dx:0},
  lines:[
    Pv('el perro, el pie de ella, el silencio'),
    N('Te quedaste callada cuando terminaste.'),
    N('No como alguien que espera respuesta.'),
    Bc(),
    SP('Como alguien que acaba de soltar algo muy pesado.'),
    N('Y necesita un momento para ver cómo se siente sin ese peso.'),
  ]},

{ lead:['Los días siguientes.', 'Él estuvo.', 'Sin más razón que esa.'],
  bg:'rio', light:'tarde', season:'otono', opts:{sun:true, tree:'otono', hill:'#8a7a4a', bank:'#9a8a52', frontBank:'#a8985a', frontBank2:'#b4a466'},
  chars:[{key:'elSit', pos:'left', sit:true, width:'50%'}, {key:'ellaSit', pos:'right', sit:true, width:'50%'}],
  dog:{pos:'center', dx:0},
  lines:[
    Pv('el río, la comida entre ellos, la tarde'),
    N('Poco a poco.'),
    N('Sin prisa.'),
    Bc(),
    N('Las tardes en el río volvieron a tener algo del peso de antes.'),
    Bc(),
    N('Pero diferente.'),
    N('Más adulto.'),
    SP('Más real.'),
  ]},

{ bg:'templo', light:'noche', season:'otono',
  chars:[{key:'elSit', pos:'left', sit:true, width:'50%'}, {key:'ellaSit', pos:'right', sit:true, width:'50%'}],
  prop:'note',
  lines:[
    E('¿Qué es?'),
    A('Todavía no sé.'),
    E('¿Cómo no sabes?'),
    A('A veces empiezas a doblar y el papel decide.'),
    Bc(),
    N('No sabía si hablabas del papel.'),
  ]},

{ bg:'templo', light:'noche', season:'otono',
  chars:[{key:'elSit', pos:'left', sit:true, width:'50%'}, {key:'ellaSit', pos:'right', sit:true, width:'50%'}],
  prop:'crane',
  lines:[
    Pv('la grulla en sus manos, las linternas'),
    N('La guardaste.'),
    Bc(),
    N('No me la diste esa noche.'),
    Bc(),
    SP('Y no pregunté.'),
    N('Aprendí que contigo las cosas llegan cuando están listas.'),
    N('No antes.'),
  ]},

{ lead:['El río.', 'Mañana.'],
  bg:'rio', light:'tarde', season:'otono', opts:{sun:true, tree:'otono', hill:'#8a7a4a', bank:'#9a8a52', frontBank:'#a8985a', frontBank2:'#b4a466'},
  chars:[{key:'elSit', pos:'left', sit:true, width:'50%'}, {key:'ellaSit', pos:'right', sit:true, width:'50%'}],
  dog:{pos:'center', dx:0}, prop:'crane',
  lines:[
    E('¿Esta es para mí?'),
    A('¿Quién más estaría aquí?', '(un momento)'),
    Bc(),
    Pv('la grulla pasando de una mano a otra'),
    N('La guardé en la caja esa noche.'),
    N('Junto a la primera.'),
    Bc(),
    N('Dos grullas.'),
    Bl(),
    SP('Y supe que íbamos a intentarlo.'),
    N('No porque lo dijéramos.'),
    N('Sino porque el papel lo había decidido.'),
    Pv(),
    SP('Y esta vez yo no iba a quedarme callado.'),
  ]},
];

window.STORY = STORY;
